# Copyright (c) 2024, AgriTheory and contributors
# For license information, please see license.txt

suppliers = [
	(
		"Freedom Provisions",
		None,
		None,
		None,
		"Net 30",
		{
			"address_line1": "16 Margrave",
			"city": "Carlisle",
			"state": "NH",
			"country": "United States",
			"pincode": "57173",
		},
	),
	(
		"Unity Bakery Supply",
		None,
		None,
		None,
		"Net 30",
		{
			"address_line1": "34 Pinar St",
			"city": "Unity",
			"state": "RI",
			"country": "United States",
			"pincode": "34291",
		},
	),
	(
		"Chelsea Fruit Co",
		None,
		None,
		None,
		"Net 30",
		{
			"address_line1": "67C Sweeny Street",
			"city": "Chelsea",
			"state": "MA",
			"country": "United States",
			"pincode": "89077",
		},
	),
	(
		"Credible Contract Baking",
		None,
		None,
		None,
		"Net 30",
		{
			"address_line1": "4 Crumb Circle",
			"city": "Belmont",
			"state": "MA",
			"country": "United States",
			"pincode": "89074",
		},
	),
	(
		"Southern Fruit Supply",
		None,
		None,
		None,
		"Net 30",
		{
			"address_line1": "10001 Pineapple Way",
			"city": "Largo",
			"state": "TX",
			"country": "United States",
			"pincode": "89574",
		},
	),
]

workstations = [
	("Mix Pie Crust Station", "20"),
	("Roll Pie Crust Station", "20"),
	("Make Pie Filling Station", "20"),
	("Cooling Station", "100"),
	("Box Pie Station", "100"),
	("Baking Station", "20"),
	("Assemble Pie Station", "20"),
	("Mix Pie Filling Station", "20"),
	("Packaging Station", "2"),
	("Food Prep Table 2", "10"),
	("Food Prep Table 1", "5"),
	("Range Station", "20"),
	("Cooling Racks Station", "80"),
	("Refrigerator Station", "200"),
	("Oven Station", "20"),
	("Mixer Station", "10"),
]

operations = [
	(
		"Gather Pie Crust Ingredients",
		"Food Prep Table 2",
		"5",
		"""- Remove flour, salt, and a pie tins from store room
	- Remove butter and ice water from refrigerator
	- Place ingredients at workstation
	- Measure amounts for batch size into mixing bowl""",
		["Food Prep Table 1"],
	),
	(
		"Gather Pie Filling Ingredients",
		"Food Prep Table 1",
		"5",
		"""- Remove fruit and butter from refrigerator
	- Remove sugar and cornstarch
	- Get water from sink
	- Measure ingredients and place in pot, excluding 1/4 of fruit and butter""",
		["Food Prep Table 2"],
	),
	(
		"Assemble Pie Op",
		"Food Prep Table 2",
		"5",
		"""- Use fresh pie filling or remove from refrigerator
	- Remove rolled pie crusts from refrigerator
	- Fill bottom crust with filling
	- Create decorative cut out for top crust
	- Layer top crust over bottom crust / filling and create a crimped seal""",
		["Food Prep Table 1", "Assemble Pie Station"],
	),
	(
		"Cook Pie Filling Operation",
		"Range Station",
		"5",
		"""- Bring ingredients to simmer and cook for 15 minutes
	- Remove from heat and mix in remaining 1/4 berries and butter
	- Store in refrigerator if not using immediately""",
	),
	(
		"Mix Dough Op",
		"Mixer Station",
		"5",
		"""- Combine flour, butter, salt, and ice water in mixer
	- Pulse for 30 seconds
	- Divide into equal-sized portions, one portion for each pie crust being made
	- Put in refrigerator""",
		["Mix Pie Crust Station", "Mix Pie Filling Station"],
	),
	("Box Pie Op", "Packaging Station", "5", "- Place pie into box for sale"),
	(
		"Roll Pie Crust Op",
		"Food Prep Table 2",
		"5",
		"""- Remove chilled pie crust portions from refrigerator
	- Separate each portion into two (one for bottom crust, one for top)
	- Flour board and roll out each portion into a circle
	- Place bottom crust into pie tin, then layer a piece of parchment paper, followed by the top crust""",
		["Food Prep Table 1", "Roll Pie Crust Station"],
	),
	("Divide Dough Op", "Food Prep Table 2", "1", "Divide Dough Op", ["Food Prep Table 1"]),
	(
		"Bake Op",
		"Oven Station",
		"1",
		"""- Place assembled pies into oven
	- Bake at 375F for 50 minutes
	- Remove from oven""",
		["Baking Station"],
	),
	(
		"Chill Pie Crust Op",
		"Refrigerator Station",
		"1",
		"- Chill pie crust for at least 30 minutes",
		["Cooling Station", "Cooling Racks Station"],
	),
	(
		"Cool Pie Op",
		"Cooling Racks Station",
		"1",
		"Cool baked pies for at least 30 minutes before boxing",
		["Cooling Station", "Refrigerator Station"],
	),
	(
		"Assemble Pocket Op",
		"Food Prep Table 1",
		"5",
		"""- Fold 3 poppers into dough pocket""",
	),
	(
		"Assemble Popper Op",
		"Food Prep Table 1",
		"5",
		"""- Top dough bite with fruit""",
	),
	(
		"Assemble Combination Product",
		"Food Prep Table 1",
		"5",
		"""- Tower: package one pie and one pocket, and one popper
    - Pocketful of Bay: package one pocket with two poppers""",
	),
]

items = [
	{
		"item_code": "Ambrosia Pie",
		"item_group": "Baked Goods",
		"uom": "Nos",
		"weight_per_unit": 7.5,
		"weight_uom": "Pound",
		"item_price": 11.00,
		"default_warehouse": "Refrigerated Display - APC",
		"description": "<div><p>Ambrosia Pie is the marquee product of Ambrosia Pie Company. A filling of heavenly cloudberries pair perfectly with the tart hairless rambutan, finished with drizzles of tayberry nectar. It's a feast fit for Mt Olympus!</p></div>",
	},
	{
		"item_code": "Double Plum Pie",
		"uom": "Nos",
		"weight_per_unit": 8,
		"weight_uom": "Pound",
		"item_group": "Baked Goods",
		"item_price": 10.50,
		"default_warehouse": "Refrigerated Display - APC",
		"description": "<div><p>Double the fun and double the flavor with our Double Plum Pie! We combine damson and cocoplums in a daring tropical-meets-temperate filling. Forbidden fruit never tasted this good.</p></div>",
	},
	{
		"item_code": "Gooseberry Pie",
		"uom": "Nos",
		"weight_per_unit": 8.5,
		"weight_uom": "Pound",
		"item_group": "Baked Goods",
		"item_price": 12.00,
		"default_warehouse": "Refrigerated Display - APC",
		"description": "<div><p>Our delicious take on the traditional gooseberry pie that tastes like the holidays. This classic pie is best shared with the ones you love.</p></div>",
	},
	{
		"item_code": "Kaduka Key Lime Pie",
		"item_group": "Baked Goods",
		"uom": "Nos",
		"weight_per_unit": 9,
		"weight_uom": "Pound",
		"item_price": 11.50,
		"default_warehouse": "Refrigerated Display - APC",
		"description": "<div><p>Take your tastebuds on an adventure with this whimsical twist on the classic Key Lime pie. Made with kaduka limes and the exotic limequat, this seasonal pie is sure to satisfy even the most weary culinary explorer. Grab it when you can - it's only available April through September.</p></div>",
	},
	{
		"item_code": "Tower of Bay-bel",
		"uom": "Nos",
		"item_group": "Baked Goods",
		"item_price": 20.00,
		"default_warehouse": "Refrigerated Display - APC",
		"description": "<div><p>Reach for the stars with this epic all-things-bayberry dessert that stacks a Bayberry Pocket on top of our Bayberry Pie.</p></div>",
	},
	{
		"item_code": "Pocketful of Bay",
		"uom": "Nos",
		"item_group": "Baked Goods",
		"item_price": 12.00,
		"default_warehouse": "Refrigerated Display - APC",
		"description": "<div><p>Try this delightful combination of a Bayberry Pocket and two additional Bayberry Poppers.</p></div>",
	},
	{
		"item_code": "Bayberry Pie",
		"uom": "Nos",
		"item_group": "Sub Assemblies",
		# "item_price": 11.00,  # can a finished good be included as sub-assembly for another good?
		"default_warehouse": "Refrigerated Display - APC",
		"description": "<div><p>This pie features the sweet and scrumptious bayberry and is sure to be a crowd-pleaser.</p></div>",
	},
	{
		"item_code": "Bayberry Pocket",
		"uom": "Nos",
		"item_group": "Sub Assemblies",
		# "item_price": 8.00,
		"default_warehouse": "Refrigerated Display - APC",
		"description": "<div><p>Need a little more than one popper? The Bayberry Pocket is a tasty dough pocket stuffed with several Bayberry Poppers.</p></div>",
	},
	{
		"item_code": "Bayberry Popper",
		"uom": "Nos",
		"item_group": "Sub Assemblies",
		# "item_price": 3.00,
		"default_warehouse": "Refrigerated Display - APC",
		"description": "<div><p>Part cookie, part tart, these bite-sized treats will bring a little sweetness to your day.</p></div>",
	},
	{
		"item_code": "Ambrosia Pie Filling",
		"uom": "Cup",
		"item_group": "Sub Assemblies",
		"default_warehouse": "Refrigerator - APC",
		"description": "Ambrosia Pie Filling",
	},
	{
		"item_code": "Double Plum Pie Filling",
		"uom": "Cup",
		"item_group": "Sub Assemblies",
		"default_warehouse": "Refrigerator - APC",
		"description": "Double Plum Pie Filling",
	},
	{
		"item_code": "Gooseberry Pie Filling",
		"uom": "Cup",
		"description": "Gooseberry Pie Filling",
		"item_group": "Sub Assemblies",
		"default_warehouse": "Refrigerator - APC",
	},
	{
		"item_code": "Bayberry Pie Filling",
		"uom": "Cup",
		"description": "Bayberry Pie Filling",
		"item_group": "Sub Assemblies",
		"default_warehouse": "Refrigerator - APC",
	},
	{
		"item_code": "Kaduka Key Lime Pie Filling",
		"item_group": "Sub Assemblies",
		"default_warehouse": "Refrigerator - APC",
		"uom": "Cup",
		"description": "Kaduka Key Lime Pie Filling",
	},
	{
		"item_code": "Pie Crust",
		"uom": "Nos",
		"description": "Pie Crust",
		"item_group": "Sub Assemblies",
		"default_warehouse": "Refrigerator - APC",
		"is_sub_contracted_item": 1,
		"item_price": 2.00,
		"default_supplier": "",
		"supplier": "",
		"valuation_rate": 3.0196,
		"uom_conversion_detail": {"Hour": 20},
	},
	{
		"item_code": "Pie Crust Service per Crust",
		"uom": "Nos",
		"description": "Subcontracted pie crust manufacturing service. Item price is per crust.",
		"item_group": "Sub Assemblies",
		"default_warehouse": "Credible Contract Baking - APC",
		"is_sub_contracted_item": 1,
		"is_stock_item": 0,
		"item_price": 2.00,
		"default_supplier": "Credible Contract Baking",
		"supplier": "Credible Contract Baking",
	},
	{
		"item_code": "Pie Crust Service per Hour",
		"uom": "Hour",
		"description": "Subcontracted pie crust manufacturing service. Item price is per hour.",
		"item_group": "Sub Assemblies",
		"default_warehouse": "Credible Contract Baking - APC",
		"is_sub_contracted_item": 1,
		"is_stock_item": 0,
		"item_price": 40.00,  # Assumes 5 crusts takes 15 mins (excluding chilling time), or 20 crusts/hour at rate of $2.00/crust
		"default_supplier": "Credible Contract Baking",
		"supplier": "Credible Contract Baking",
	},
	{
		"item_code": "Cloudberry",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Cloudberry",
		"item_group": "Ingredients",
		"item_price": 0.65,
		"default_warehouse": "Refrigerator - APC",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Cocoplum",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Cocoplum",
		"item_group": "Ingredients",
		"item_price": 0.35,
		"default_warehouse": "Refrigerator - APC",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Damson Plum",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Damson Plum",
		"item_group": "Ingredients",
		"item_price": 0.85,
		"default_warehouse": "Refrigerator - APC",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Gooseberry",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Gooseberry",
		"item_group": "Ingredients",
		"item_price": 0.99,
		"default_warehouse": "Refrigerator - APC",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Hairless Rambutan",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Hairless Rambutan",
		"item_price": 0.50,
		"item_group": "Ingredients",
		"default_warehouse": "Storeroom - APC",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Kaduka Lime",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Kaduka Lime",
		"item_group": "Ingredients",
		"item_price": 0.89,
		"default_warehouse": "Refrigerator - APC",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Limequat",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Limequat",
		"item_group": "Ingredients",
		"item_price": 0.75,
		"default_warehouse": "Refrigerator - APC",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Tayberry",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Tayberry",
		"item_group": "Ingredients",
		"item_price": 0.85,
		"default_warehouse": "Refrigerator - APC",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Bayberry",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Bayberry",
		"item_group": "Ingredients",
		"item_price": 0.45,
		"default_warehouse": "Refrigerator - APC",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Butter",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Butter",
		"item_group": "Ingredients",
		"item_price": 4.5,
		"default_warehouse": "Refrigerator - APC",
		"supplier": [
			"Freedom Provisions",
			"Chelsea Fruit Co",
		],
	},
	{
		"item_code": "Cornstarch",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Cornstarch",
		"item_group": "Ingredients",
		"item_price": 0.52,
		"default_warehouse": "Storeroom - APC",
		"supplier": "Freedom Provisions",
	},
	{
		"item_code": "Ice Water",
		"uom": "Cup",
		"weight_uom": "Pound",
		"weight_per_unit": 0.52,
		"description": "Ice Water - necessary for pie crusts",
		"item_group": "Ingredients",
		"item_price": 0.01,
		"default_warehouse": "Refrigerator - APC",
		"available_in_house": 1,
		"opening_qty": 50,
	},
	{
		"item_code": "Flour",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Flour",
		"item_group": "Ingredients",
		"item_price": 0.66,
		"default_warehouse": "Storeroom - APC",
		"supplier": "Freedom Provisions",
	},
	{
		"item_code": "Pie Box",
		"uom": "Nos",
		"description": "Pie Box",
		"item_group": "Bakery Supplies",
		"item_price": 0.4,
		"default_warehouse": "Storeroom - APC",
		"supplier": ["Freedom Provisions", "Unity Bakery Supply"],
	},
	{
		"item_code": "Pie Tin",
		"uom": "Nos",
		"description": "Pie Tin",
		"item_price": 0.18,
		"item_group": "Bakery Supplies",
		"default_warehouse": "Storeroom - APC",
		"supplier": ["Freedom Provisions", "Unity Bakery Supply"],
	},
	{
		"item_code": "Parchment Paper",
		"uom": "Nos",
		"description": "Parchment Paper",
		"item_group": "Bakery Supplies",
		"item_price": 0.02,
		"default_warehouse": "Storeroom - APC",
		"supplier": ["Freedom Provisions", "Unity Bakery Supply"],
		"uom_conversion_detail": {"Box": 100},
	},
	{
		"item_code": "Salt",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Salt",
		"item_group": "Ingredients",
		"item_price": 0.36,
		"default_warehouse": "Storeroom - APC",
		"supplier": "Freedom Provisions",
	},
	{
		"item_code": "Sugar",
		"uom": "Pound",
		"weight_uom": "Pound",
		"weight_per_unit": 1,
		"description": "Sugar",
		"item_group": "Ingredients",
		"item_price": 0.60,
		"default_warehouse": "Storeroom - APC",
		"supplier": "Freedom Provisions",
	},
	{
		"item_code": "Water",
		"uom": "Cup",
		"weight_uom": "Pound",
		"weight_per_unit": 0.52,
		"item_price": 0.05,
		"description": "Water",
		"item_group": "Ingredients",
		"default_warehouse": "Kitchen - APC",
		"available_in_house": 1,
		"opening_qty": 50,
	},
	{
		"item_code": "Bilberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.5,
		"weight_uom": "Pound",
		"item_price": 0.52,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, deep-blue berry with a tart flavor, perfect for jams and desserts.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Kepel",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.2,
		"weight_uom": "Pound",
		"item_price": 0.93,
		"default_warehouse": "Refrigerator - APC",
		"description": "A rare tropical fruit with a sweet, mango-like taste and an exotic aroma.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Lime",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 10.0,
		"weight_uom": "Pound",
		"item_price": 0.15,
		"default_warehouse": "Refrigerator - APC",
		"description": "A zesty citrus fruit packed with tangy juice, ideal for drinks and seasoning.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Boquila",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 4.8,
		"weight_uom": "Pound",
		"item_price": 0.72,
		"default_warehouse": "Refrigerator - APC",
		"description": "A unique fruit with a mild sweetness, known for its adaptive vine behavior.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Bael",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 15.5,
		"weight_uom": "Pound",
		"item_price": 0.61,
		"default_warehouse": "Refrigerator - APC",
		"description": "A hard-shelled fruit with fragrant, fibrous pulp, often used in refreshing drinks.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Highbush Cranberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.2,
		"weight_uom": "Pound",
		"item_price": 0.21,
		"default_warehouse": "Refrigerator - APC",
		"description": "A tart, bright red berry commonly used in jellies and sauces.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Sambucus",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.8,
		"weight_uom": "Pound",
		"item_price": 0.83,
		"default_warehouse": "Refrigerator - APC",
		"description": "Also known as elderberry, these tiny dark berries are rich in antioxidants.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Redcurrant",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 4.5,
		"weight_uom": "Pound",
		"item_price": 0.87,
		"default_warehouse": "Refrigerator - APC",
		"description": "A bright, juicy berry with a refreshing tartness, great for jams and syrups.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Gac",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 12.8,
		"weight_uom": "Pound",
		"item_price": 0.75,
		"default_warehouse": "Refrigerator - APC",
		"description": "A spiky, orange fruit packed with nutrients and a mild, subtly sweet flavor.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "European Blueberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.2,
		"weight_uom": "Pound",
		"item_price": 0.75,
		"default_warehouse": "Refrigerator - APC",
		"description": "A wild berry with a deep blue hue and a slightly tangy-sweet taste.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Giant Granadilla",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 18.5,
		"weight_uom": "Pound",
		"item_price": 0.88,
		"default_warehouse": "Refrigerator - APC",
		"description": "A large passion fruit with fragrant pulp and a tropical sweetness.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Bearberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 4.2,
		"weight_uom": "Pound",
		"item_price": 0.24,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, bright red berry with a mildly tart taste, often used in herbal teas.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Seedless Watermelon",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 25.0,
		"weight_uom": "Pound",
		"item_price": 0.03,
		"default_warehouse": "Refrigerator - APC",
		"description": "A juicy, refreshing fruit with sweet red flesh, perfect for summer.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Mini Watermelon",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 8.5,
		"weight_uom": "Pound",
		"item_price": 0.22,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, personal-sized watermelon bursting with refreshing sweetness.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Kandis",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.8,
		"weight_uom": "Pound",
		"item_price": 0.53,
		"default_warehouse": "Refrigerator - APC",
		"description": "A sour tropical fruit often used to add tangy depth to dishes and drinks.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Berberis Vulgaris",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.0,
		"weight_uom": "Pound",
		"item_price": 0.02,
		"default_warehouse": "Refrigerator - APC",
		"description": "Also known as barberry, a tart red berry used in Middle Eastern cuisine.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Blue Tongue",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.5,
		"weight_uom": "Pound",
		"item_price": 0.88,
		"default_warehouse": "Refrigerator - APC",
		"description": "A wild Australian fruit with a mild sweetness and a striking blue pulp.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Kahikatea",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 9.2,
		"weight_uom": "Pound",
		"item_price": 0.3,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, fleshy fruit from New Zealand with a subtly sweet taste.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Kabosu",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 8.8,
		"weight_uom": "Pound",
		"item_price": 0.38,
		"default_warehouse": "Refrigerator - APC",
		"description": "A Japanese citrus fruit with a zesty, aromatic juice, often used in cooking.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Kaffir Lime",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.0,
		"weight_uom": "Pound",
		"item_price": 0.02,
		"default_warehouse": "Refrigerator - APC",
		"description": "A fragrant citrus fruit with bumpy skin, prized for its intensely aromatic zest.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Black Apple",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 9.5,
		"weight_uom": "Pound",
		"item_price": 0.64,
		"default_warehouse": "Refrigerator - APC",
		"description": "A rare, dark-hued apple with a crisp texture and a rich, sweet flavor.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Black Cherry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.5,
		"weight_uom": "Pound",
		"item_price": 0.6,
		"default_warehouse": "Refrigerator - APC",
		"description": "A juicy, dark cherry with a deep sweetness and a touch of tartness.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Lychee",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 8.0,
		"weight_uom": "Pound",
		"item_price": 0.21,
		"default_warehouse": "Refrigerator - APC",
		"description": "A tropical fruit with a fragrant, floral sweetness and a juicy texture.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Jostaberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.8,
		"weight_uom": "Pound",
		"item_price": 0.33,
		"default_warehouse": "Refrigerator - APC",
		"description": "A hybrid berry combining the tartness of gooseberries with the sweetness of currants.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Camu Camu",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.2,
		"weight_uom": "Pound",
		"item_price": 0.76,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, tangy fruit with exceptionally high vitamin C content.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Batuan",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.8,
		"weight_uom": "Pound",
		"item_price": 0.58,
		"default_warehouse": "Refrigerator - APC",
		"description": "A sour fruit used in Southeast Asian cuisine to add a tangy kick to dishes.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Calamondin",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.2,
		"weight_uom": "Pound",
		"item_price": 0.22,
		"default_warehouse": "Refrigerator - APC",
		"description": "A tiny citrus fruit with a bright, tart juice, often used in drinks and marinades.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Citron",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 12.5,
		"weight_uom": "Pound",
		"item_price": 0.89,
		"default_warehouse": "Refrigerator - APC",
		"description": "A large citrus fruit with thick rind, valued for its aromatic zest and mild juice.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Coco Plum",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 9.8,
		"weight_uom": "Pound",
		"item_price": 0.49,
		"default_warehouse": "Refrigerator - APC",
		"description": "A sweet, plum-like fruit often enjoyed fresh or made into preserves.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Horned Melon",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 11.2,
		"weight_uom": "Pound",
		"item_price": 0.91,
		"default_warehouse": "Refrigerator - APC",
		"description": "A spiky fruit with bright orange skin and jelly-like, tart-sweet flesh.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Fragaria",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 4.8,
		"weight_uom": "Pound",
		"item_price": 0.59,
		"default_warehouse": "Refrigerator - APC",
		"description": "The scientific name for strawberries, known for their bright red sweetness.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Boysenberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.5,
		"weight_uom": "Pound",
		"item_price": 0.42,
		"default_warehouse": "Refrigerator - APC",
		"description": "A juicy, dark purple berry with a balance of tartness and sweetness.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Chokeberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.2,
		"weight_uom": "Pound",
		"item_price": 0.92,
		"default_warehouse": "Refrigerator - APC",
		"description": "A highly astringent berry with deep antioxidant properties, often used in juices.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Raisin",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.0,
		"weight_uom": "Pound",
		"item_price": 0.6,
		"default_warehouse": "Refrigerator - APC",
		"description": "A dried grape with concentrated sweetness, commonly used in snacks and baking.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Lawton Blackberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.8,
		"weight_uom": "Pound",
		"item_price": 0.8,
		"default_warehouse": "Refrigerator - APC",
		"description": "A plump, juicy blackberry variety with a rich, sweet-tart flavor.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Cranberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.5,
		"weight_uom": "Pound",
		"item_price": 0.15,
		"default_warehouse": "Refrigerator - APC",
		"description": "A tart, ruby-red berry known for its health benefits and use in sauces.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Bilimbi",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.0,
		"weight_uom": "Pound",
		"item_price": 0.62,
		"default_warehouse": "Refrigerator - APC",
		"description": "A sour, green fruit commonly used in cooking to add acidity to dishes.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Barbados Cherry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.8,
		"weight_uom": "Pound",
		"item_price": 0.62,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, bright red fruit with a tangy-sweet flavor and high vitamin C.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Photinia",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.5,
		"weight_uom": "Pound",
		"item_price": 0.47,
		"default_warehouse": "Refrigerator - APC",
		"description": "A fruit-bearing shrub with small, colorful berries, often ornamental rather than edible.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Doubah",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 8.2,
		"weight_uom": "Pound",
		"item_price": 0.62,
		"default_warehouse": "Refrigerator - APC",
		"description": "A lesser-known tropical fruit with a rich, nutty flavor and creamy texture.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Coffee",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 10.5,
		"weight_uom": "Pound",
		"item_price": 0.51,
		"default_warehouse": "Refrigerator - APC",
		"description": "The small, red berry that contains coffee beans, the source of the beloved drink.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Youngberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.5,
		"weight_uom": "Pound",
		"item_price": 0.55,
		"default_warehouse": "Refrigerator - APC",
		"description": "A hybrid berry with a dark, juicy sweetness, similar to blackberries.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Bacuri",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 14.2,
		"weight_uom": "Pound",
		"item_price": 0.64,
		"default_warehouse": "Refrigerator - APC",
		"description": "A thick-skinned fruit with a creamy, tangy pulp enjoyed fresh or in desserts.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Louvi",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 8.8,
		"weight_uom": "Pound",
		"item_price": 0.03,
		"default_warehouse": "Refrigerator - APC",
		"description": "A rare, little-known fruit with a mild flavor and versatile culinary use.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Jaltomata Procumbens",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.2,
		"weight_uom": "Pound",
		"item_price": 0.51,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, berry-like fruit with a sweet and slightly earthy taste.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Empetrum",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 4.5,
		"weight_uom": "Pound",
		"item_price": 0.07,
		"default_warehouse": "Refrigerator - APC",
		"description": "Also known as crowberry, a small, dark fruit with a mildly tart flavor.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "European Raspberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.2,
		"weight_uom": "Pound",
		"item_price": 0.21,
		"default_warehouse": "Refrigerator - APC",
		"description": "A classic red berry with a delicate sweetness and subtle tang.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Black Raspberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.0,
		"weight_uom": "Pound",
		"item_price": 0.73,
		"default_warehouse": "Refrigerator - APC",
		"description": "A dark, antioxidant-rich berry with a complex, mildly tart sweetness.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Cryptocarya Alba",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 9.0,
		"weight_uom": "Pound",
		"item_price": 0.39,
		"default_warehouse": "Refrigerator - APC",
		"description": "A fruit-bearing tree producing small, aromatic berries with herbal notes.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Canary Melon",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 15.5,
		"weight_uom": "Pound",
		"item_price": 0.18,
		"default_warehouse": "Refrigerator - APC",
		"description": "A bright yellow melon with crisp, mildly sweet flesh.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Biriba",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 11.8,
		"weight_uom": "Pound",
		"item_price": 0.04,
		"default_warehouse": "Refrigerator - APC",
		"description": "A tropical fruit with creamy, custard-like pulp and a banana-like sweetness.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Cocky Apple",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 10.2,
		"weight_uom": "Pound",
		"item_price": 0.89,
		"default_warehouse": "Refrigerator - APC",
		"description": "An Australian fruit with a firm texture and a unique tart flavor.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Edible Honeysuckle",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.8,
		"weight_uom": "Pound",
		"item_price": 0.6,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, blue berry with a sweet, juicy taste and high antioxidant content.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Whinberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 4.8,
		"weight_uom": "Pound",
		"item_price": 0.14,
		"default_warehouse": "Refrigerator - APC",
		"description": "A wild European berry, similar to bilberries, with a rich tart-sweet taste.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Desert Lime",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.2,
		"weight_uom": "Pound",
		"item_price": 0.09,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, tangy citrus fruit native to Australia, used in jams and drinks.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Myrciaria Floribunda",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.5,
		"weight_uom": "Pound",
		"item_price": 0.9,
		"default_warehouse": "Refrigerator - APC",
		"description": "A Brazilian fruit with a sweet, grape-like flavor.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Physalis",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.5,
		"weight_uom": "Pound",
		"item_price": 0.53,
		"default_warehouse": "Refrigerator - APC",
		"description": "A golden berry enclosed in a papery husk, offering a sweet-tart bite.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Bitter Melon",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 12.0,
		"weight_uom": "Pound",
		"item_price": 0.02,
		"default_warehouse": "Refrigerator - APC",
		"description": "A bumpy, green fruit with an intense bitterness, often used in Asian cuisine.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Dabai",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 8.5,
		"weight_uom": "Pound",
		"item_price": 0.84,
		"default_warehouse": "Refrigerator - APC",
		"description": "A Malaysian fruit with a rich, creamy texture and a mild nutty flavor.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Beach Plum",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.8,
		"weight_uom": "Pound",
		"item_price": 0.92,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, coastal fruit with a tart-sweet taste, often made into jams.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Melon Pear",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 13.5,
		"weight_uom": "Pound",
		"item_price": 0.6,
		"default_warehouse": "Refrigerator - APC",
		"description": "A juicy fruit resembling both melon and cucumber in taste and texture.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Blood Orange",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 12.0,
		"weight_uom": "Pound",
		"item_price": 0.71,
		"default_warehouse": "Refrigerator - APC",
		"description": "A citrus fruit with deep red flesh and a bold, berry-like citrus flavor.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Banana",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 20.0,
		"weight_uom": "Pound",
		"item_price": 0.44,
		"default_warehouse": "Refrigerator - APC",
		"description": "A soft, sweet fruit with a creamy texture, loved worldwide as a snack.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Loquat",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 8.2,
		"weight_uom": "Pound",
		"item_price": 0.08,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, golden fruit with a mildly sweet, slightly tangy flavor.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Eugenia Uniflora",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.8,
		"weight_uom": "Pound",
		"item_price": 0.47,
		"default_warehouse": "Refrigerator - APC",
		"description": "Also known as Surinam cherry, a tropical fruit with a sharp, sweet-tart taste.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Kakadu Lime",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.0,
		"weight_uom": "Pound",
		"item_price": 0.35,
		"default_warehouse": "Refrigerator - APC",
		"description": "An Australian citrus fruit packed with tart juice and intense aroma.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Karonda",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.5,
		"weight_uom": "Pound",
		"item_price": 0.78,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, sour fruit often used in pickles and preserves.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Hippophae",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.2,
		"weight_uom": "Pound",
		"item_price": 0.81,
		"default_warehouse": "Refrigerator - APC",
		"description": "Also called sea buckthorn, a bright orange berry rich in nutrients and tartness.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Guava",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 11.5,
		"weight_uom": "Pound",
		"item_price": 0.36,
		"default_warehouse": "Refrigerator - APC",
		"description": "A fragrant tropical fruit with soft, pink or white flesh and a sweet-tart taste.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Candlenut",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 9.8,
		"weight_uom": "Pound",
		"item_price": 0.5,
		"default_warehouse": "Refrigerator - APC",
		"description": "A nut-like fruit used in cooking, known for its high oil content.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Tomatillo",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 8.5,
		"weight_uom": "Pound",
		"item_price": 0.04,
		"default_warehouse": "Refrigerator - APC",
		"description": "A green, husk-covered fruit with a tangy, citrusy flavor, used in salsas.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Olallieberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.5,
		"weight_uom": "Pound",
		"item_price": 0.02,
		"default_warehouse": "Refrigerator - APC",
		"description": "A hybrid berry with a deep, rich sweetness, perfect for desserts.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Date",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 8.8,
		"weight_uom": "Pound",
		"item_price": 0.06,
		"default_warehouse": "Refrigerator - APC",
		"description": "A chewy, naturally sweet fruit often used as a sugar substitute.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Midyim",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.2,
		"weight_uom": "Pound",
		"item_price": 0.54,
		"default_warehouse": "Refrigerator - APC",
		"description": "A tiny Australian berry with a juicy, slightly spiced sweetness.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Cowberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 4.8,
		"weight_uom": "Pound",
		"item_price": 0.04,
		"default_warehouse": "Refrigerator - APC",
		"description": "A tart red berry, commonly used in jams and sauces.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Kapok",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.2,
		"weight_uom": "Pound",
		"item_price": 0.54,
		"default_warehouse": "Refrigerator - APC",
		"description": "A tree fruit with cotton-like fibers surrounding small, edible seeds.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Durian",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 35.0,
		"weight_uom": "Pound",
		"item_price": 0.93,
		"default_warehouse": "Refrigerator - APC",
		"description": "A divisive tropical fruit with a creamy texture and an intense aroma.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Desert Banana",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 18.5,
		"weight_uom": "Pound",
		"item_price": 0.63,
		"default_warehouse": "Refrigerator - APC",
		"description": "A hardy, drought-tolerant banana variety with a rich, sweet flavor.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Coconut",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 30.0,
		"weight_uom": "Pound",
		"item_price": 0.18,
		"default_warehouse": "Refrigerator - APC",
		"description": "A versatile tropical fruit with refreshing water and creamy white flesh.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Triphasia Brassii",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 7.8,
		"weight_uom": "Pound",
		"item_price": 0.9,
		"default_warehouse": "Refrigerator - APC",
		"description": "A citrus relative with tiny, aromatic fruits used in preserves.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Kiwifruit",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 12.0,
		"weight_uom": "Pound",
		"item_price": 0.44,
		"default_warehouse": "Refrigerator - APC",
		"description": "A fuzzy brown fruit with bright green flesh and a sweet-tart flavor.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Hackberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.5,
		"weight_uom": "Pound",
		"item_price": 0.34,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, crunchy berry with a mildly sweet, nutty taste.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Genip",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 8.2,
		"weight_uom": "Pound",
		"item_price": 0.74,
		"default_warehouse": "Refrigerator - APC",
		"description": "A tart, jelly-like tropical fruit often eaten fresh.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Goji",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.8,
		"weight_uom": "Pound",
		"item_price": 0.62,
		"default_warehouse": "Refrigerator - APC",
		"description": "A nutrient-rich red berry known for its slightly sweet, earthy taste.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Clementine",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 10.5,
		"weight_uom": "Pound",
		"item_price": 0.14,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, easy-peel citrus fruit with juicy, sweet segments.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Huckleberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 4.5,
		"weight_uom": "Pound",
		"item_price": 0.95,
		"default_warehouse": "Refrigerator - APC",
		"description": "A wild berry with a rich, slightly tart flavor, great for pies.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Sultana",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 6.0,
		"weight_uom": "Pound",
		"item_price": 0.48,
		"default_warehouse": "Refrigerator - APC",
		"description": "A seedless, golden raisin known for its natural sweetness.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Bacupari",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 9.2,
		"weight_uom": "Pound",
		"item_price": 0.15,
		"default_warehouse": "Refrigerator - APC",
		"description": "A small, yellow fruit with tangy, citrus-like pulp.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "White Currant",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 4.8,
		"weight_uom": "Pound",
		"item_price": 0.72,
		"default_warehouse": "Refrigerator - APC",
		"description": "A translucent berry with a mild, delicate sweetness.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
	{
		"item_code": "Raspberry",
		"item_group": "Ingredients",
		"uom": "Pound",
		"weight_per_unit": 5.0,
		"weight_uom": "Pound",
		"item_price": 0.78,
		"default_warehouse": "Refrigerator - APC",
		"description": "A juicy, red berry with a perfect balance of sweetness and tang.",
		"supplier": ["Chelsea Fruit Co", "Southern Fruit Supply"],
	},
]

boms = [
	{
		"item": "Tower of Bay-bel",
		"quantity": 5.0,
		"uom": "Nos",
		"items": [
			{"item_code": "Bayberry Pie", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
			{"item_code": "Bayberry Pocket", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Assemble Combination Product",
				"time_in_mins": 2.0,
				"workstation": "Food Prep Table 1",
			},
		],
	},
	{
		"item": "Pocketful of Bay",
		"quantity": 5.0,
		"uom": "Nos",
		"items": [
			{"item_code": "Bayberry Pocket", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
			{"item_code": "Bayberry Popper", "qty": 10.0, "qty_consumed_per_unit": 2.0, "uom": "Nos"},
			{"item_code": "Pie Box", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Assemble Combination Product",
				"time_in_mins": 2.0,
				"workstation": "Food Prep Table 1",
			},
		],
	},
	{
		"item": "Bayberry Pocket",
		"quantity": 5.0,
		"uom": "Nos",
		"items": [
			{"item_code": "Flour", "qty": 1.5, "qty_consumed_per_unit": 0.3, "uom": "Pound"},
			{"item_code": "Butter", "qty": 0.75, "qty_consumed_per_unit": 0.15, "uom": "Pound"},
			{"item_code": "Sugar", "qty": 0.1, "qty_consumed_per_unit": 0.02, "uom": "Pound"},
			{"item_code": "Bayberry Popper", "qty": 15.0, "qty_consumed_per_unit": 3.0, "uom": "Nos"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Mix Dough Op",
				"time_in_mins": 5.0,
				"workstation": "Mixer Station",
			},
			{
				"batch_size": 5,
				"operation": "Assemble Pocket Op",
				"time_in_mins": 2.0,
				"workstation": "Food Prep Table 1",
			},
		],
	},
	{
		"item": "Bayberry Popper",
		"quantity": 5.0,
		"uom": "Nos",
		"items": [
			{"item_code": "Flour", "qty": 0.5, "qty_consumed_per_unit": 0.1, "uom": "Pound"},
			{"item_code": "Butter", "qty": 0.25, "qty_consumed_per_unit": 0.05, "uom": "Pound"},
			{"item_code": "Sugar", "qty": 0.05, "qty_consumed_per_unit": 0.01, "uom": "Pound"},
			{"item_code": "Bayberry", "qty": 1.0, "qty_consumed_per_unit": 0.2, "uom": "Pound"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Mix Dough Op",
				"time_in_mins": 5.0,
				"workstation": "Mixer Station",
			},
			{
				"batch_size": 5,
				"operation": "Assemble Popper Op",
				"time_in_mins": 1.0,
				"workstation": "Food Prep Table 1",
			},
		],
	},
	{
		"item": "Bayberry Pie",
		"quantity": 5.0,
		"uom": "Nos",
		"items": [
			{"item_code": "Pie Crust", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
			{
				"item_code": "Bayberry Pie Filling",
				"qty": 20.0,
				"qty_consumed_per_unit": 4.0,
				"uom": "Cup",
			},
			{"item_code": "Pie Box", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Assemble Pie Op",
				"time_in_mins": 10.0,
				"workstation": "Food Prep Table 2",
			},
			{"batch_size": 1, "operation": "Bake Op", "time_in_mins": 50.0, "workstation": "Oven Station"},
			{
				"batch_size": 1,
				"operation": "Cool Pie Op",
				"time_in_mins": 30.0,
				"workstation": "Cooling Racks Station",
			},
			{
				"batch_size": 5,
				"operation": "Box Pie Op",
				"time_in_mins": 5.0,
				"workstation": "Packaging Station",
			},
		],
	},
	{
		"item": "Double Plum Pie",
		"quantity": 5.0,
		"uom": "Nos",
		"items": [
			{"item_code": "Pie Crust", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
			{
				"item_code": "Double Plum Pie Filling",
				"qty": 20.0,
				"qty_consumed_per_unit": 4.0,
				"uom": "Cup",
			},
			{"item_code": "Pie Box", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Assemble Pie Op",
				"time_in_mins": 10.0,
				"workstation": "Food Prep Table 2",
			},
			{"batch_size": 1, "operation": "Bake Op", "time_in_mins": 50.0, "workstation": "Oven Station"},
			{
				"batch_size": 1,
				"operation": "Cool Pie Op",
				"time_in_mins": 30.0,
				"workstation": "Cooling Racks Station",
			},
			{
				"batch_size": 5,
				"operation": "Box Pie Op",
				"time_in_mins": 5.0,
				"workstation": "Packaging Station",
			},
		],
	},
	{
		"item": "Kaduka Key Lime Pie",
		"quantity": 5.0,
		"uom": "Nos",
		"items": [
			{"item_code": "Pie Crust", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
			{
				"item_code": "Kaduka Key Lime Pie Filling",
				"qty": 20.0,
				"qty_consumed_per_unit": 4.0,
				"uom": "Cup",
			},
			{"item_code": "Pie Box", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Assemble Pie Op",
				"time_in_mins": 10.0,
				"workstation": "Food Prep Table 2",
			},
			{"batch_size": 1, "operation": "Bake Op", "time_in_mins": 50.0, "workstation": "Oven Station"},
			{
				"batch_size": 1,
				"operation": "Cool Pie Op",
				"time_in_mins": 30.0,
				"workstation": "Cooling Racks Station",
			},
			{
				"batch_size": 5,
				"operation": "Box Pie Op",
				"time_in_mins": 5.0,
				"workstation": "Packaging Station",
			},
		],
	},
	{
		"item": "Gooseberry Pie",
		"quantity": 5.0,
		"uom": "Nos",
		"items": [
			{"item_code": "Pie Crust", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
			{
				"item_code": "Gooseberry Pie Filling",
				"qty": 20.0,
				"qty_consumed_per_unit": 4.0,
				"uom": "Cup",
			},
			{"item_code": "Pie Box", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Assemble Pie Op",
				"time_in_mins": 10.0,
				"workstation": "Food Prep Table 2",
			},
			{"batch_size": 1, "operation": "Bake Op", "time_in_mins": 50.0, "workstation": "Oven Station"},
			{
				"batch_size": 1,
				"operation": "Cool Pie Op",
				"time_in_mins": 30.0,
				"workstation": "Cooling Racks Station",
			},
			{
				"batch_size": 5,
				"operation": "Box Pie Op",
				"time_in_mins": 5.0,
				"workstation": "Packaging Station",
			},
		],
	},
	{
		"item": "Ambrosia Pie",
		"quantity": 5.0,
		"uom": "Nos",
		"overproduction_percentage_for_work_order": 100,
		"items": [
			{"item_code": "Pie Crust", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
			{"item_code": "Ambrosia Pie Filling", "qty": 20.0, "qty_consumed_per_unit": 4.0, "uom": "Cup"},
			{"item_code": "Pie Box", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Assemble Pie Op",
				"time_in_mins": 10.0,
				"workstation": "Food Prep Table 2",
			},
			{"batch_size": 1, "operation": "Bake Op", "time_in_mins": 50.0, "workstation": "Oven Station"},
			{
				"batch_size": 1,
				"operation": "Cool Pie Op",
				"time_in_mins": 30.0,
				"workstation": "Cooling Racks Station",
			},
			{
				"batch_size": 5,
				"operation": "Box Pie Op",
				"time_in_mins": 5.0,
				"workstation": "Packaging Station",
			},
		],
	},
	{
		"item": "Bayberry Pie Filling",
		"quantity": 20.0,
		"uom": "Cup",
		"items": [
			{"item_code": "Sugar", "qty": 0.5, "qty_consumed_per_unit": 0.025, "uom": "Pound"},
			{"item_code": "Cornstarch", "qty": 0.1, "qty_consumed_per_unit": 0.005, "uom": "Pound"},
			{"item_code": "Water", "qty": 1.25, "qty_consumed_per_unit": 0.0625, "uom": "Cup"},
			{"item_code": "Butter", "qty": 0.313, "qty_consumed_per_unit": 0.01565, "uom": "Pound"},
			{"item_code": "Bayberry", "qty": 15.0, "qty_consumed_per_unit": 0.05025, "uom": "Pound"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Gather Pie Filling Ingredients",
				"time_in_mins": 5.0,
				"workstation": "Food Prep Table 1",
			},
			{
				"batch_size": 5,
				"operation": "Cook Pie Filling Operation",
				"time_in_mins": 15.0,
				"workstation": "Range Station",
			},
		],
	},
	{
		"item": "Double Plum Pie Filling",
		"quantity": 20.0,
		"uom": "Cup",
		"items": [
			{"item_code": "Sugar", "qty": 0.5, "qty_consumed_per_unit": 0.025, "uom": "Pound"},
			{"item_code": "Cornstarch", "qty": 0.1, "qty_consumed_per_unit": 0.005, "uom": "Pound"},
			{"item_code": "Water", "qty": 1.25, "qty_consumed_per_unit": 0.0625, "uom": "Cup"},
			{"item_code": "Butter", "qty": 0.313, "qty_consumed_per_unit": 0.01565, "uom": "Pound"},
			{"item_code": "Cocoplum", "qty": 7.5, "qty_consumed_per_unit": 0.02515, "uom": "Pound"},
			{"item_code": "Damson Plum", "qty": 7.5, "qty_consumed_per_unit": 0.02515, "uom": "Pound"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Gather Pie Filling Ingredients",
				"time_in_mins": 5.0,
				"workstation": "Food Prep Table 1",
			},
			{
				"batch_size": 5,
				"operation": "Cook Pie Filling Operation",
				"time_in_mins": 15.0,
				"workstation": "Range Station",
			},
		],
	},
	{
		"item": "Kaduka Key Lime Pie Filling",
		"quantity": 20.0,
		"uom": "Cup",
		"items": [
			{"item_code": "Sugar", "qty": 0.5, "qty_consumed_per_unit": 0.025, "uom": "Pound"},
			{"item_code": "Cornstarch", "qty": 0.1, "qty_consumed_per_unit": 0.005, "uom": "Pound"},
			{"item_code": "Water", "qty": 1.25, "qty_consumed_per_unit": 0.0625, "uom": "Cup"},
			{"item_code": "Butter", "qty": 0.313, "qty_consumed_per_unit": 0.01565, "uom": "Pound"},
			{"item_code": "Kaduka Lime", "qty": 10.0, "qty_consumed_per_unit": 0.0335, "uom": "Pound"},
			{"item_code": "Limequat", "qty": 5.0, "qty_consumed_per_unit": 0.01675, "uom": "Pound"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Gather Pie Filling Ingredients",
				"time_in_mins": 5.0,
				"workstation": "Food Prep Table 1",
			},
			{
				"batch_size": 5,
				"operation": "Cook Pie Filling Operation",
				"time_in_mins": 15.0,
				"workstation": "Range Station",
			},
		],
	},
	{
		"item": "Gooseberry Pie Filling",
		"quantity": 20.0,
		"uom": "Cup",
		"items": [
			{"item_code": "Sugar", "qty": 0.5, "qty_consumed_per_unit": 0.025, "uom": "Pound"},
			{"item_code": "Cornstarch", "qty": 0.1, "qty_consumed_per_unit": 0.005, "uom": "Pound"},
			{"item_code": "Water", "qty": 1.25, "qty_consumed_per_unit": 0.0625, "uom": "Cup"},
			{"item_code": "Butter", "qty": 0.313, "qty_consumed_per_unit": 0.01565, "uom": "Pound"},
			{"item_code": "Gooseberry", "qty": 15.0, "qty_consumed_per_unit": 0.05025, "uom": "Pound"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Gather Pie Filling Ingredients",
				"time_in_mins": 5.0,
				"workstation": "Food Prep Table 1",
			},
			{
				"batch_size": 5,
				"operation": "Cook Pie Filling Operation",
				"time_in_mins": 15.0,
				"workstation": "Range Station",
			},
		],
	},
	{
		"item": "Ambrosia Pie Filling",
		"quantity": 20.0,
		"uom": "Cup",
		"items": [
			{"item_code": "Sugar", "qty": 0.5, "qty_consumed_per_unit": 0.025, "uom": "Pound"},
			{"item_code": "Cornstarch", "qty": 0.1, "qty_consumed_per_unit": 0.005, "uom": "Pound"},
			{"item_code": "Butter", "qty": 0.313, "qty_consumed_per_unit": 0.01565, "uom": "Pound"},
			{
				"item_code": "Hairless Rambutan",
				"qty": 5.0,
				"qty_consumed_per_unit": 0.01675,
				"uom": "Pound",
			},
			{"item_code": "Tayberry", "qty": 2.5, "qty_consumed_per_unit": 0.0084, "uom": "Pound"},
			{"item_code": "Cloudberry", "qty": 7.5, "qty_consumed_per_unit": 0.02515, "uom": "Pound"},
			{"item_code": "Water", "qty": 1.25, "qty_consumed_per_unit": 0.0625, "uom": "Cup"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Gather Pie Filling Ingredients",
				"time_in_mins": 5.0,
				"workstation": "Food Prep Table 1",
			},
			{
				"batch_size": 5,
				"operation": "Cook Pie Filling Operation",
				"time_in_mins": 15.0,
				"workstation": "Range Station",
			},
		],
	},
	{
		"item": "Pie Crust",  # Subcontracted BOM
		"quantity": 5.0,
		"uom": "Nos",
		"is_default": 0,
		"is_subcontracted": 1,
		"with_operations": 0,
		"items": [
			{"item_code": "Flour", "qty": 4.25, "qty_consumed_per_unit": 0.85, "uom": "Pound"},
			{"item_code": "Butter", "qty": 2.5, "qty_consumed_per_unit": 0.5, "uom": "Pound"},
			# {"item_code": "Ice Water", "qty": 2.5, "qty_consumed_per_unit": 0.5, "uom": "Cup"},
			{"item_code": "Salt", "qty": 0.05, "qty_consumed_per_unit": 0.01, "uom": "Pound"},
			{"item_code": "Parchment Paper", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
			{"item_code": "Pie Tin", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
		],
		"operations": [],  # Subcontracted item -> operations done by supplier
	},
	{
		"item": "Pie Crust",  # In-house BOM
		"quantity": 5.0,
		"uom": "Nos",
		"items": [
			{"item_code": "Flour", "qty": 4.25, "qty_consumed_per_unit": 0.85, "uom": "Pound"},
			{"item_code": "Butter", "qty": 2.5, "qty_consumed_per_unit": 0.5, "uom": "Pound"},
			{"item_code": "Ice Water", "qty": 2.5, "qty_consumed_per_unit": 0.5, "uom": "Cup"},
			{"item_code": "Salt", "qty": 0.05, "qty_consumed_per_unit": 0.01, "uom": "Pound"},
			{"item_code": "Parchment Paper", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
			{"item_code": "Pie Tin", "qty": 5.0, "qty_consumed_per_unit": 1.0, "uom": "Nos"},
		],
		"operations": [
			{
				"batch_size": 5,
				"operation": "Gather Pie Crust Ingredients",
				"time_in_mins": 5.0,
				"workstation": "Food Prep Table 2",
			},
			{
				"batch_size": 5,
				"operation": "Mix Dough Op",
				"time_in_mins": 5.0,
				"workstation": "Mixer Station",
			},
			{
				"batch_size": 1,
				"operation": "Divide Dough Op",
				"time_in_mins": 2.0,
				"workstation": "Food Prep Table 2",
			},
			{
				"batch_size": 1,
				"operation": "Chill Pie Crust Op",
				"time_in_mins": 30.0,
				"workstation": "Refrigerator Station",
			},
			{
				"batch_size": 5,
				"operation": "Roll Pie Crust Op",
				"time_in_mins": 10.0,
				"workstation": "Food Prep Table 2",
			},
		],
	},
]

customers = [
	"Almacs Food Group",
	"Beans and Dreams Roasters",
	"Cafe 27 Cafeteria",
	"Capital Grille Restaurant Group",
	"Downtown Deli",
	"Draws Groceries",
	"Grab n Go Bodega",
	"Grand North Station Baking Co",
	"Happy Basket Food Distribution Group",
	"Jitter Cafe",
	"Longwoods Sandwich Shop",
	"Midtown Munchies Inc",
	"My Way Cup Coffee",
	"Nom Nom Cafe",
	"Round the World Donut Shop",
	"Sand Street Deli",
	"Starfood Cafe",
	"Terrywood Terminal Bakery Inc",
	"TransAmerica Bank Cafeteria",
	"Whole Harvest Grocery Group",
]

specifications = [
	{
		"dt": "Item",
		"name": "Items",
		"apply_on": "",
		"enabled": 1,
		"attributes": [
			{
				"attribute_name": "Color",
				"applied_on": "Item",
				"component": "FacetedSearchColorPicker",
			},
			{
				"attribute_name": "Weight",
				"applied_on": "Item",
				"field": "weight_per_unit",
				"numeric_values": 1,
				"component": "FacetedSearchNumericRange",
			},
			{
				"attribute_name": "Brand",
				"applied_on": "Item",
				"field": "brand",
				"component": "AttributeFilter",
			},
		],
	},
	{
		"dt": "Item Group",
		"name": "Baked Goods",
		"apply_on": "Baked Goods",
		"enabled": 1,
		"attributes": [
			{
				"attribute_name": "Price",
				"applied_on": "Item",
				"numeric_values": 1,
				"component": "FacetedSearchNumericRange",
			},
			{"attribute_name": "Fruits", "applied_on": "Item", "component": "AttributeFilter"},
			{
				"attribute_name": "Shelf Life",
				"applied_on": "Item",
				"field": "shelf_life_in_days",
				"numeric_values": 1,
				"component": "FacetedSearchNumericRange",
			},
			{
				"attribute_name": "EOL",
				"applied_on": "Item",
				"field": "end_of_life",
				"date_values": 1,
				"component": "FacetedSearchDateRange",
			},
		],
	},
]


attributes = {
	"Ambrosia Pie": {
		"Fruits": ["Hairless Rambutan", "Cloudberry", "Tayberry"],
		"Price": 11.00,
		"Color": ["Blue", "Red"],
		"Brand": "Chelsea Fruit Co",
	},
	"Double Plum Pie": {
		"Fruits": ["Cocoplum", "Damson Plum"],
		"Price": 10.50,
		"Color": ["Purple"],
		"Brand": "Chelsea Fruit Co",
	},
	"Gooseberry Pie": {
		"Fruits": "Gooseberry",
		"Price": 12.00,
		"Color": ["Yellow"],
		"Brand": "Chelsea Fruit Co",
	},
	"Kaduka Key Lime Pie": {
		"Fruits": ["Kaduka Lime", "Limequat"],
		"Price": 11.50,
		"Color": ["Green", "Yellow"],
		"Brand": "Chelsea Fruit Co",
	},
	"Tayberry": {
		"Color": ["Red"],
	},
	"Limequat": {
		"Color": ["Yellow", "Green"],
	},
	"Kaduka Lime": {
		"Color": ["Green"],
	},
	"Hairless Rambutan": {
		"Color": ["Red"],
	},
	"Gooseberry": {
		"Color": ["Yellow"],
	},
	"Damson Plum": {
		"Color": ["Purple"],
	},
	"Cocoplum": {
		"Color": ["Purple", "Black"],
	},
	"Bayberry": {
		"Color": ["Red", "Green", "Blue"],
	},
	"Sugar": {
		"Color": ["White"],
	},
	"Salt": {
		"Color": ["White"],
	},
	"Flour": {
		"Color": ["White"],
	},
	"Cornstarch": {
		"Color": ["White"],
	},
	"Butter": {
		"Color": ["Yellow"],
	},
	"Cloudberry": {
		"Color": ["Yellow", "Red"],
	},
}

item_dimensions = [
	{
		"name": "Bilberry",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bilberry",
		"uom": "Box",
	},
	{
		"name": "Kepel",
		"item_length": 14.2,
		"item_height": 5.1,
		"item_width": 9.5,
		"item_weight": 7.2,
		"dimension_type": "Exterior",
		"case_height": 5.1,
		"case_width": 9.5,
		"case_length": 14.2,
		"case_weight": 7.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kepel",
		"uom": "Box",
	},
	{
		"name": "Lime",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 10.0,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 10.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Lime",
		"uom": "Box",
	},
	{
		"name": "Boquila",
		"item_length": 11.8,
		"item_height": 4.0,
		"item_width": 7.9,
		"item_weight": 4.8,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 7.9,
		"case_length": 11.8,
		"case_weight": 4.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Boquila",
		"uom": "Box",
	},
	{
		"name": "Bael",
		"item_length": 18.2,
		"item_height": 8.3,
		"item_width": 12.5,
		"item_weight": 15.5,
		"dimension_type": "Exterior",
		"case_height": 8.3,
		"case_width": 12.5,
		"case_length": 18.2,
		"case_weight": 15.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bael",
		"uom": "Box",
	},
	{
		"name": "Highbush Cranberry",
		"item_length": 13.1,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.2,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.1,
		"case_weight": 6.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Highbush Cranberry",
		"uom": "Box",
	},
	{
		"name": "Sambucus",
		"item_length": 12.8,
		"item_height": 4.3,
		"item_width": 8.5,
		"item_weight": 5.8,
		"dimension_type": "Exterior",
		"case_height": 4.3,
		"case_width": 8.5,
		"case_length": 12.8,
		"case_weight": 5.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Sambucus",
		"uom": "Box",
	},
	{
		"name": "Redcurrant",
		"item_length": 11.5,
		"item_height": 3.9,
		"item_width": 7.7,
		"item_weight": 4.5,
		"dimension_type": "Exterior",
		"case_height": 3.9,
		"case_width": 7.7,
		"case_length": 11.5,
		"case_weight": 4.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Redcurrant",
		"uom": "Box",
	},
	{
		"name": "Gac",
		"item_length": 16.5,
		"item_height": 7.2,
		"item_width": 11.2,
		"item_weight": 12.8,
		"dimension_type": "Exterior",
		"case_height": 7.2,
		"case_width": 11.2,
		"case_length": 16.5,
		"case_weight": 12.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Gac",
		"uom": "Box",
	},
	{
		"name": "European Blueberry",
		"item_length": 12.2,
		"item_height": 4.1,
		"item_width": 8.1,
		"item_weight": 5.2,
		"dimension_type": "Exterior",
		"case_height": 4.1,
		"case_width": 8.1,
		"case_length": 12.2,
		"case_weight": 5.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "European Blueberry",
		"uom": "Box",
	},
	{
		"name": "Giant Granadilla",
		"item_length": 20.5,
		"item_height": 9.5,
		"item_width": 14.2,
		"item_weight": 18.5,
		"dimension_type": "Exterior",
		"case_height": 9.5,
		"case_width": 14.2,
		"case_length": 20.5,
		"case_weight": 18.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Giant Granadilla",
		"uom": "Box",
	},
	{
		"name": "Bearberry",
		"item_length": 11.2,
		"item_height": 3.8,
		"item_width": 7.5,
		"item_weight": 4.2,
		"dimension_type": "Exterior",
		"case_height": 3.8,
		"case_width": 7.5,
		"case_length": 11.2,
		"case_weight": 4.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bearberry",
		"uom": "Box",
	},
	{
		"name": "Seedless Watermelon",
		"item_length": 24.0,
		"item_height": 12.0,
		"item_width": 16.0,
		"item_weight": 25.0,
		"dimension_type": "Exterior",
		"case_height": 12.0,
		"case_width": 16.0,
		"case_length": 24.0,
		"case_weight": 25.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Seedless Watermelon",
		"uom": "Box",
	},
	{
		"name": "Mini Watermelon",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.5,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Mini Watermelon",
		"uom": "Box",
	},
	{
		"name": "Kandis",
		"item_length": 13.5,
		"item_height": 4.6,
		"item_width": 9.0,
		"item_weight": 6.8,
		"dimension_type": "Exterior",
		"case_height": 4.6,
		"case_width": 9.0,
		"case_length": 13.5,
		"case_weight": 6.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kandis",
		"uom": "Box",
	},
	{
		"name": "Berberis Vulgaris",
		"item_length": 12.0,
		"item_height": 4.0,
		"item_width": 8.0,
		"item_weight": 5.0,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 8.0,
		"case_length": 12.0,
		"case_weight": 5.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Berberis Vulgaris",
		"uom": "Box",
	},
	{
		"name": "Blue Tongue",
		"item_length": 14.5,
		"item_height": 5.2,
		"item_width": 9.7,
		"item_weight": 7.5,
		"dimension_type": "Exterior",
		"case_height": 5.2,
		"case_width": 9.7,
		"case_length": 14.5,
		"case_weight": 7.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Blue Tongue",
		"uom": "Box",
	},
	{
		"name": "Kahikatea",
		"item_length": 15.5,
		"item_height": 6.5,
		"item_width": 10.5,
		"item_weight": 9.2,
		"dimension_type": "Exterior",
		"case_height": 6.5,
		"case_width": 10.5,
		"case_length": 15.5,
		"case_weight": 9.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kahikatea",
		"uom": "Box",
	},
	{
		"name": "Kabosu",
		"item_length": 15.2,
		"item_height": 6.2,
		"item_width": 10.2,
		"item_weight": 8.8,
		"dimension_type": "Exterior",
		"case_height": 6.2,
		"case_width": 10.2,
		"case_length": 15.2,
		"case_weight": 8.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kabosu",
		"uom": "Box",
	},
	{
		"name": "Kaffir Lime",
		"item_length": 13.8,
		"item_height": 4.8,
		"item_width": 9.2,
		"item_weight": 7.0,
		"dimension_type": "Exterior",
		"case_height": 4.8,
		"case_width": 9.2,
		"case_length": 13.8,
		"case_weight": 7.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kaffir Lime",
		"uom": "Box",
	},
	{
		"name": "Black Apple",
		"item_length": 15.8,
		"item_height": 6.8,
		"item_width": 10.7,
		"item_weight": 9.5,
		"dimension_type": "Exterior",
		"case_height": 6.8,
		"case_width": 10.7,
		"case_length": 15.8,
		"case_weight": 9.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Black Apple",
		"uom": "Box",
	},
	{
		"name": "Black Cherry",
		"item_length": 13.2,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.5,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.2,
		"case_weight": 6.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Black Cherry",
		"uom": "Box",
	},
	{
		"name": "Lychee",
		"item_length": 14.8,
		"item_height": 5.5,
		"item_width": 9.9,
		"item_weight": 8.0,
		"dimension_type": "Exterior",
		"case_height": 5.5,
		"case_width": 9.9,
		"case_length": 14.8,
		"case_weight": 8.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Lychee",
		"uom": "Box",
	},
	{
		"name": "Jostaberry",
		"item_length": 12.8,
		"item_height": 4.3,
		"item_width": 8.5,
		"item_weight": 5.8,
		"dimension_type": "Exterior",
		"case_height": 4.3,
		"case_width": 8.5,
		"case_length": 12.8,
		"case_weight": 5.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Jostaberry",
		"uom": "Box",
	},
	{
		"name": "Camu Camu",
		"item_length": 13.1,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.2,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.1,
		"case_weight": 6.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Camu Camu",
		"uom": "Box",
	},
	{
		"name": "Batuan",
		"item_length": 14.6,
		"item_height": 5.4,
		"item_width": 9.8,
		"item_weight": 7.8,
		"dimension_type": "Exterior",
		"case_height": 5.4,
		"case_width": 9.8,
		"case_length": 14.6,
		"case_weight": 7.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Batuan",
		"uom": "Box",
	},
	{
		"name": "Calamondin",
		"item_length": 14.2,
		"item_height": 5.1,
		"item_width": 9.5,
		"item_weight": 7.2,
		"dimension_type": "Exterior",
		"case_height": 5.1,
		"case_width": 9.5,
		"case_length": 14.2,
		"case_weight": 7.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Calamondin",
		"uom": "Box",
	},
	{
		"name": "Citron",
		"item_length": 16.2,
		"item_height": 7.0,
		"item_width": 11.0,
		"item_weight": 12.5,
		"dimension_type": "Exterior",
		"case_height": 7.0,
		"case_width": 11.0,
		"case_length": 16.2,
		"case_weight": 12.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Citron",
		"uom": "Box",
	},
	{
		"name": "Coco Plum",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 9.8,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 9.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Coco Plum",
		"uom": "Box",
	},
	{
		"name": "Horned Melon",
		"item_length": 16.5,
		"item_height": 7.2,
		"item_width": 11.2,
		"item_weight": 11.2,
		"dimension_type": "Exterior",
		"case_height": 7.2,
		"case_width": 11.2,
		"case_length": 16.5,
		"case_weight": 11.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Horned Melon",
		"uom": "Box",
	},
	{
		"name": "Fragaria",
		"item_length": 11.8,
		"item_height": 4.0,
		"item_width": 7.9,
		"item_weight": 4.8,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 7.9,
		"case_length": 11.8,
		"case_weight": 4.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Fragaria",
		"uom": "Box",
	},
	{
		"name": "Boysenberry",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Boysenberry",
		"uom": "Box",
	},
	{
		"name": "Chokeberry",
		"item_length": 12.2,
		"item_height": 4.1,
		"item_width": 8.1,
		"item_weight": 5.2,
		"dimension_type": "Exterior",
		"case_height": 4.1,
		"case_width": 8.1,
		"case_length": 12.2,
		"case_weight": 5.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Chokeberry",
		"uom": "Box",
	},
	{
		"name": "Raisin",
		"item_length": 13.0,
		"item_height": 4.4,
		"item_width": 8.7,
		"item_weight": 6.0,
		"dimension_type": "Exterior",
		"case_height": 4.4,
		"case_width": 8.7,
		"case_length": 13.0,
		"case_weight": 6.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Raisin",
		"uom": "Box",
	},
	{
		"name": "Lawton Blackberry",
		"item_length": 12.8,
		"item_height": 4.3,
		"item_width": 8.5,
		"item_weight": 5.8,
		"dimension_type": "Exterior",
		"case_height": 4.3,
		"case_width": 8.5,
		"case_length": 12.8,
		"case_weight": 5.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Lawton Blackberry",
		"uom": "Box",
	},
	{
		"name": "Cranberry",
		"item_length": 13.2,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.5,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.2,
		"case_weight": 6.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cranberry",
		"uom": "Box",
	},
	{
		"name": "Bilimbi",
		"item_length": 13.8,
		"item_height": 4.8,
		"item_width": 9.2,
		"item_weight": 7.0,
		"dimension_type": "Exterior",
		"case_height": 4.8,
		"case_width": 9.2,
		"case_length": 13.8,
		"case_weight": 7.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bilimbi",
		"uom": "Box",
	},
	{
		"name": "Barbados Cherry",
		"item_length": 13.5,
		"item_height": 4.6,
		"item_width": 9.0,
		"item_weight": 6.8,
		"dimension_type": "Exterior",
		"case_height": 4.6,
		"case_width": 9.0,
		"case_length": 13.5,
		"case_weight": 6.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Barbados Cherry",
		"uom": "Box",
	},
	{
		"name": "Photinia",
		"item_length": 14.5,
		"item_height": 5.2,
		"item_width": 9.7,
		"item_weight": 7.5,
		"dimension_type": "Exterior",
		"case_height": 5.2,
		"case_width": 9.7,
		"case_length": 14.5,
		"case_weight": 7.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Photinia",
		"uom": "Box",
	},
	{
		"name": "Doubah",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.2,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Doubah",
		"uom": "Box",
	},
	{
		"name": "Coffee",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 10.5,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 10.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Coffee",
		"uom": "Box",
	},
	{
		"name": "Youngberry",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Youngberry",
		"uom": "Box",
	},
	{
		"name": "Bacuri",
		"item_length": 17.5,
		"item_height": 8.0,
		"item_width": 12.0,
		"item_weight": 14.2,
		"dimension_type": "Exterior",
		"case_height": 8.0,
		"case_width": 12.0,
		"case_length": 17.5,
		"case_weight": 14.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bacuri",
		"uom": "Box",
	},
	{
		"name": "Louvi",
		"item_length": 15.2,
		"item_height": 6.2,
		"item_width": 10.2,
		"item_weight": 8.8,
		"dimension_type": "Exterior",
		"case_height": 6.2,
		"case_width": 10.2,
		"case_length": 15.2,
		"case_weight": 8.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Louvi",
		"uom": "Box",
	},
	{
		"name": "Jaltomata Procumbens",
		"item_length": 13.1,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.2,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.1,
		"case_weight": 6.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Jaltomata Procumbens",
		"uom": "Box",
	},
	{
		"name": "Empetrum",
		"item_length": 11.5,
		"item_height": 3.9,
		"item_width": 7.7,
		"item_weight": 4.5,
		"dimension_type": "Exterior",
		"case_height": 3.9,
		"case_width": 7.7,
		"case_length": 11.5,
		"case_weight": 4.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Empetrum",
		"uom": "Box",
	},
	{
		"name": "European Raspberry",
		"item_length": 12.2,
		"item_height": 4.1,
		"item_width": 8.1,
		"item_weight": 5.2,
		"dimension_type": "Exterior",
		"case_height": 4.1,
		"case_width": 8.1,
		"case_length": 12.2,
		"case_weight": 5.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "European Raspberry",
		"uom": "Box",
	},
	{
		"name": "Black Raspberry",
		"item_length": 12.0,
		"item_height": 4.0,
		"item_width": 8.0,
		"item_weight": 5.0,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 8.0,
		"case_length": 12.0,
		"case_weight": 5.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Black Raspberry",
		"uom": "Box",
	},
	{
		"name": "Cryptocarya Alba",
		"item_length": 15.5,
		"item_height": 6.5,
		"item_width": 10.5,
		"item_weight": 9.0,
		"dimension_type": "Exterior",
		"case_height": 6.5,
		"case_width": 10.5,
		"case_length": 15.5,
		"case_weight": 9.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cryptocarya Alba",
		"uom": "Box",
	},
	{
		"name": "Canary Melon",
		"item_length": 18.2,
		"item_height": 8.3,
		"item_width": 12.5,
		"item_weight": 15.5,
		"dimension_type": "Exterior",
		"case_height": 8.3,
		"case_width": 12.5,
		"case_length": 18.2,
		"case_weight": 15.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Canary Melon",
		"uom": "Box",
	},
	{
		"name": "Biriba",
		"item_length": 16.8,
		"item_height": 7.4,
		"item_width": 11.4,
		"item_weight": 11.8,
		"dimension_type": "Exterior",
		"case_height": 7.4,
		"case_width": 11.4,
		"case_length": 16.8,
		"case_weight": 11.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Biriba",
		"uom": "Box",
	},
	{
		"name": "Cocky Apple",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 10.2,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 10.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cocky Apple",
		"uom": "Box",
	},
	{
		"name": "Edible Honeysuckle",
		"item_length": 12.8,
		"item_height": 4.3,
		"item_width": 8.5,
		"item_weight": 5.8,
		"dimension_type": "Exterior",
		"case_height": 4.3,
		"case_width": 8.5,
		"case_length": 12.8,
		"case_weight": 5.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Edible Honeysuckle",
		"uom": "Box",
	},
	{
		"name": "Whinberry",
		"item_length": 11.8,
		"item_height": 4.0,
		"item_width": 7.9,
		"item_weight": 4.8,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 7.9,
		"case_length": 11.8,
		"case_weight": 4.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Whinberry",
		"uom": "Box",
	},
	{
		"name": "Desert Lime",
		"item_length": 14.2,
		"item_height": 5.1,
		"item_width": 9.5,
		"item_weight": 7.2,
		"dimension_type": "Exterior",
		"case_height": 5.1,
		"case_width": 9.5,
		"case_length": 14.2,
		"case_weight": 7.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Desert Lime",
		"uom": "Box",
	},
	{
		"name": "Myrciaria Floribunda",
		"item_length": 13.2,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.5,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.2,
		"case_weight": 6.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Myrciaria Floribunda",
		"uom": "Box",
	},
	{
		"name": "Physalis",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Physalis",
		"uom": "Box",
	},
	{
		"name": "Bitter Melon",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 12.0,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 12.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bitter Melon",
		"uom": "Box",
	},
	{
		"name": "Dabai",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.5,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Dabai",
		"uom": "Box",
	},
	{
		"name": "Beach Plum",
		"item_length": 14.6,
		"item_height": 5.4,
		"item_width": 9.8,
		"item_weight": 7.8,
		"dimension_type": "Exterior",
		"case_height": 5.4,
		"case_width": 9.8,
		"case_length": 14.6,
		"case_weight": 7.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Beach Plum",
		"uom": "Box",
	},
	{
		"name": "Melon Pear",
		"item_length": 17.0,
		"item_height": 7.5,
		"item_width": 11.5,
		"item_weight": 13.5,
		"dimension_type": "Exterior",
		"case_height": 7.5,
		"case_width": 11.5,
		"case_length": 17.0,
		"case_weight": 13.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Melon Pear",
		"uom": "Box",
	},
	{
		"name": "Blood Orange",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 12.0,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 12.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Blood Orange",
		"uom": "Box",
	},
	{
		"name": "Banana",
		"item_length": 22.0,
		"item_height": 10.0,
		"item_width": 15.0,
		"item_weight": 20.0,
		"dimension_type": "Exterior",
		"case_height": 10.0,
		"case_width": 15.0,
		"case_length": 22.0,
		"case_weight": 20.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Banana",
		"uom": "Box",
	},
	{
		"name": "Loquat",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.2,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Loquat",
		"uom": "Box",
	},
	{
		"name": "Eugenia Uniflora",
		"item_length": 13.5,
		"item_height": 4.6,
		"item_width": 9.0,
		"item_weight": 6.8,
		"dimension_type": "Exterior",
		"case_height": 4.6,
		"case_width": 9.0,
		"case_length": 13.5,
		"case_weight": 6.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Eugenia Uniflora",
		"uom": "Box",
	},
	{
		"name": "Kakadu Lime",
		"item_length": 13.8,
		"item_height": 4.8,
		"item_width": 9.2,
		"item_weight": 7.0,
		"dimension_type": "Exterior",
		"case_height": 4.8,
		"case_width": 9.2,
		"case_length": 13.8,
		"case_weight": 7.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kakadu Lime",
		"uom": "Box",
	},
	{
		"name": "Karonda",
		"item_length": 14.5,
		"item_height": 5.2,
		"item_width": 9.7,
		"item_weight": 7.5,
		"dimension_type": "Exterior",
		"case_height": 5.2,
		"case_width": 9.7,
		"case_length": 14.5,
		"case_weight": 7.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Karonda",
		"uom": "Box",
	},
	{
		"name": "Hippophae",
		"item_length": 13.1,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.2,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.1,
		"case_weight": 6.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Hippophae",
		"uom": "Box",
	},
	{
		"name": "Guava",
		"item_length": 16.5,
		"item_height": 7.2,
		"item_width": 11.2,
		"item_weight": 11.5,
		"dimension_type": "Exterior",
		"case_height": 7.2,
		"case_width": 11.2,
		"case_length": 16.5,
		"case_weight": 11.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Guava",
		"uom": "Box",
	},
	{
		"name": "Candlenut",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 9.8,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 9.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Candlenut",
		"uom": "Box",
	},
	{
		"name": "Tomatillo",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.5,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Tomatillo",
		"uom": "Box",
	},
	{
		"name": "Olallieberry",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Olallieberry",
		"uom": "Box",
	},
	{
		"name": "Date",
		"item_length": 15.2,
		"item_height": 6.2,
		"item_width": 10.2,
		"item_weight": 8.8,
		"dimension_type": "Exterior",
		"case_height": 6.2,
		"case_width": 10.2,
		"case_length": 15.2,
		"case_weight": 8.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Date",
		"uom": "Box",
	},
	{
		"name": "Midyim",
		"item_length": 12.2,
		"item_height": 4.1,
		"item_width": 8.1,
		"item_weight": 5.2,
		"dimension_type": "Exterior",
		"case_height": 4.1,
		"case_width": 8.1,
		"case_length": 12.2,
		"case_weight": 5.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Midyim",
		"uom": "Box",
	},
	{
		"name": "Cowberry",
		"item_length": 11.8,
		"item_height": 4.0,
		"item_width": 7.9,
		"item_weight": 4.8,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 7.9,
		"case_length": 11.8,
		"case_weight": 4.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cowberry",
		"uom": "Box",
	},
	{
		"name": "Kapok",
		"item_length": 14.2,
		"item_height": 5.1,
		"item_width": 9.5,
		"item_weight": 7.2,
		"dimension_type": "Exterior",
		"case_height": 5.1,
		"case_width": 9.5,
		"case_length": 14.2,
		"case_weight": 7.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kapok",
		"uom": "Box",
	},
	{
		"name": "Durian",
		"item_length": 28.0,
		"item_height": 15.0,
		"item_width": 20.0,
		"item_weight": 35.0,
		"dimension_type": "Exterior",
		"case_height": 15.0,
		"case_width": 20.0,
		"case_length": 28.0,
		"case_weight": 35.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Durian",
		"uom": "Box",
	},
	{
		"name": "Desert Banana",
		"item_length": 20.5,
		"item_height": 9.5,
		"item_width": 14.2,
		"item_weight": 18.5,
		"dimension_type": "Exterior",
		"case_height": 9.5,
		"case_width": 14.2,
		"case_length": 20.5,
		"case_weight": 18.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Desert Banana",
		"uom": "Box",
	},
	{
		"name": "Coconut",
		"item_length": 26.0,
		"item_height": 13.0,
		"item_width": 18.0,
		"item_weight": 30.0,
		"dimension_type": "Exterior",
		"case_height": 13.0,
		"case_width": 18.0,
		"case_length": 26.0,
		"case_weight": 30.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Coconut",
		"uom": "Box",
	},
	{
		"name": "Triphasia Brassii",
		"item_length": 14.6,
		"item_height": 5.4,
		"item_width": 9.8,
		"item_weight": 7.8,
		"dimension_type": "Exterior",
		"case_height": 5.4,
		"case_width": 9.8,
		"case_length": 14.6,
		"case_weight": 7.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Triphasia Brassii",
		"uom": "Box",
	},
	{
		"name": "Kiwifruit",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 12.0,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 12.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kiwifruit",
		"uom": "Box",
	},
	{
		"name": "Hackberry",
		"item_length": 13.2,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.5,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.2,
		"case_weight": 6.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Hackberry",
		"uom": "Box",
	},
	{
		"name": "Genip",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.2,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Genip",
		"uom": "Box",
	},
	{
		"name": "Goji",
		"item_length": 12.8,
		"item_height": 4.3,
		"item_width": 8.5,
		"item_weight": 5.8,
		"dimension_type": "Exterior",
		"case_height": 4.3,
		"case_width": 8.5,
		"case_length": 12.8,
		"case_weight": 5.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Goji",
		"uom": "Box",
	},
	{
		"name": "Clementine",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 10.5,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 10.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Clementine",
		"uom": "Box",
	},
	{
		"name": "Huckleberry",
		"item_length": 11.5,
		"item_height": 3.9,
		"item_width": 7.7,
		"item_weight": 4.5,
		"dimension_type": "Exterior",
		"case_height": 3.9,
		"case_width": 7.7,
		"case_length": 11.5,
		"case_weight": 4.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Huckleberry",
		"uom": "Box",
	},
	{
		"name": "Sultana",
		"item_length": 13.0,
		"item_height": 4.4,
		"item_width": 8.7,
		"item_weight": 6.0,
		"dimension_type": "Exterior",
		"case_height": 4.4,
		"case_width": 8.7,
		"case_length": 13.0,
		"case_weight": 6.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Sultana",
		"uom": "Box",
	},
	{
		"name": "Hairless Rambutan",
		"item_length": 15.8,
		"item_height": 6.8,
		"item_width": 10.7,
		"item_weight": 9.5,
		"dimension_type": "Exterior",
		"case_height": 6.8,
		"case_width": 10.7,
		"case_length": 15.8,
		"case_weight": 9.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Hairless Rambutan",
		"uom": "Box",
	},
	{
		"name": "Tayberry",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Tayberry",
		"uom": "Box",
	},
	{
		"name": "Gooseberry",
		"item_length": 12.2,
		"item_height": 4.1,
		"item_width": 8.1,
		"item_weight": 5.2,
		"dimension_type": "Exterior",
		"case_height": 4.1,
		"case_width": 8.1,
		"case_length": 12.2,
		"case_weight": 5.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Gooseberry",
		"uom": "Box",
	},
	{
		"name": "Cocoplum",
		"item_length": 15.2,
		"item_height": 6.2,
		"item_width": 10.2,
		"item_weight": 8.8,
		"dimension_type": "Exterior",
		"case_height": 6.2,
		"case_width": 10.2,
		"case_length": 15.2,
		"case_weight": 8.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cocoplum",
		"uom": "Box",
	},
	{
		"name": "Damson Plum",
		"item_length": 14.5,
		"item_height": 5.2,
		"item_width": 9.7,
		"item_weight": 7.5,
		"dimension_type": "Exterior",
		"case_height": 5.2,
		"case_width": 9.7,
		"case_length": 14.5,
		"case_weight": 7.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Damson Plum",
		"uom": "Box",
	},
	{
		"name": "Bacupari",
		"item_length": 15.5,
		"item_height": 6.5,
		"item_width": 10.5,
		"item_weight": 9.2,
		"dimension_type": "Exterior",
		"case_height": 6.5,
		"case_width": 10.5,
		"case_length": 15.5,
		"case_weight": 9.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bacupari",
		"uom": "Box",
	},
	{
		"name": "White Currant",
		"item_length": 11.8,
		"item_height": 4.0,
		"item_width": 7.9,
		"item_weight": 4.8,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 7.9,
		"case_length": 11.8,
		"case_weight": 4.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "White Currant",
		"uom": "Box",
	},
	{
		"name": "Raspberry",
		"item_length": 12.0,
		"item_height": 4.0,
		"item_width": 8.0,
		"item_weight": 5.0,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 8.0,
		"case_length": 12.0,
		"case_weight": 5.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Raspberry",
		"uom": "Box",
	},
	{
		"name": "Limequat",
		"item_length": 14.2,
		"item_height": 5.1,
		"item_width": 9.5,
		"item_weight": 7.2,
		"dimension_type": "Exterior",
		"case_height": 5.1,
		"case_width": 9.5,
		"case_length": 14.2,
		"case_weight": 7.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Limequat",
		"uom": "Box",
	},
	{
		"name": "Cloudberry",
		"item_length": 11.2,
		"item_height": 3.8,
		"item_width": 7.5,
		"item_weight": 4.2,
		"dimension_type": "Exterior",
		"case_height": 3.8,
		"case_width": 7.5,
		"case_length": 11.2,
		"case_weight": 4.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cloudberry",
		"uom": "Box",
	},
]
