# Copyright (c) 2024, AgriTheory and contributors
# For license information, please see license.txt

suppliers = [
	(
		"Freedom Provisions",
		None,
		None,
		None,
		"Net 30",
		{
			"address_line1": "16 Margrave",
			"city": "Carlisle",
			"state": "NH",
			"country": "United States",
			"pincode": "57173",
		},
	),
	(
		"Unity Bakery Supply",
		None,
		None,
		None,
		"Net 30",
		{
			"address_line1": "34 Pinar St",
			"city": "Unity",
			"state": "RI",
			"country": "United States",
			"pincode": "34291",
		},
	),
	(
		"Chelsea Fruit Co",
		None,
		None,
		None,
		"Net 30",
		{
			"address_line1": "67C Sweeny Street",
			"city": "Chelsea",
			"state": "MA",
			"country": "United States",
			"pincode": "89077",
		},
	),
	(
		"Credible Contract Baking",
		None,
		None,
		None,
		"Net 30",
		{
			"address_line1": "4 Crumb Circle",
			"city": "Belmont",
			"state": "MA",
			"country": "United States",
			"pincode": "89074",
		},
	),
	(
		"Southern Fruit Supply",
		None,
		None,
		None,
		"Net 30",
		{
			"address_line1": "10001 Pineapple Way",
			"city": "Largo",
			"state": "TX",
			"country": "United States",
			"pincode": "89574",
		},
	),
]

workstations = [
	("Mix Pie Crust Station", "20", "mixer.png", "mixer.png"),
	("Roll Pie Crust Station", "20", "rolling.png", "rolling.png"),
	("Make Pie Filling Station", "20", "table.png", "table.png"),
	("Cooling Station", "100", "rack.png", "rack.png"),
	("Box Pie Station", "100", "box.png", "box.png"),
	("Baking Station", "20", "oven.png", "oven.png"),
	("Assemble Pie Station", "20", "table.png", "table.png"),
	("Mix Pie Filling Station", "20", "mixer.png", "mixer.png"),
	("Packaging Station", "2", "box.png", "box.png"),
	("Food Prep Table 2", "10", "table.png", "table.png"),
	("Food Prep Table 1", "5", "table.png", "table.png"),
	("Range Station", "20", "range.png", "range.png"),
	("Cooling Racks Station", "80", "rack.png", "rack.png"),
	("Refrigerator Station", "200", "fridge.png", "fridge.png"),
	("Oven Station", "20", "oven.png", "oven.png"),
	("Mixer Station", "10", "mixer.png", "mixer.png"),
]

operations = [
	(
		"Gather Pie Crust Ingredients",
		"Food Prep Table 2",
		"5",
		"""- Remove flour, salt, and a pie tins from store room
	- Remove butter and ice water from refrigerator
	- Place ingredients at workstation
	- Measure amounts for batch size into mixing bowl""",
		["Food Prep Table 1"],
	),
	(
		"Gather Pie Filling Ingredients",
		"Food Prep Table 1",
		"5",
		"""- Remove fruit and butter from refrigerator
	- Remove sugar and cornstarch
	- Get water from sink
	- Measure ingredients and place in pot, excluding 1/4 of fruit and butter""",
		["Food Prep Table 2"],
	),
	(
		"Assemble Pie Op",
		"Food Prep Table 2",
		"5",
		"""- Use fresh pie filling or remove from refrigerator
	- Remove rolled pie crusts from refrigerator
	- Fill bottom crust with filling
	- Create decorative cut out for top crust
	- Layer top crust over bottom crust / filling and create a crimped seal""",
		["Food Prep Table 1", "Assemble Pie Station"],
	),
	(
		"Cook Pie Filling Operation",
		"Range Station",
		"5",
		"""- Bring ingredients to simmer and cook for 15 minutes
	- Remove from heat and mix in remaining 1/4 berries and butter
	- Store in refrigerator if not using immediately""",
	),
	(
		"Mix Dough Op",
		"Mixer Station",
		"5",
		"""- Combine flour, butter, salt, and ice water in mixer
	- Pulse for 30 seconds
	- Divide into equal-sized portions, one portion for each pie crust being made
	- Put in refrigerator""",
		["Mix Pie Crust Station", "Mix Pie Filling Station"],
	),
	("Box Pie Op", "Packaging Station", "5", "- Place pie into box for sale"),
	(
		"Roll Pie Crust Op",
		"Food Prep Table 2",
		"5",
		"""- Remove chilled pie crust portions from refrigerator
	- Separate each portion into two (one for bottom crust, one for top)
	- Flour board and roll out each portion into a circle
	- Place bottom crust into pie tin, then layer a piece of parchment paper, followed by the top crust""",
		["Food Prep Table 1", "Roll Pie Crust Station"],
	),
	("Divide Dough Op", "Food Prep Table 2", "1", "Divide Dough Op", ["Food Prep Table 1"]),
	(
		"Bake Op",
		"Oven Station",
		"1",
		"""- Place assembled pies into oven
	- Bake at 375F for 50 minutes
	- Remove from oven""",
		["Baking Station"],
	),
	(
		"Chill Pie Crust Op",
		"Refrigerator Station",
		"1",
		"- Chill pie crust for at least 30 minutes",
		["Cooling Station", "Cooling Racks Station"],
	),
	(
		"Cool Pie Op",
		"Cooling Racks Station",
		"1",
		"Cool baked pies for at least 30 minutes before boxing",
		["Cooling Station", "Refrigerator Station"],
	),
	(
		"Assemble Pocket Op",
		"Food Prep Table 1",
		"5",
		"""- Fold 3 poppers into dough pocket""",
	),
	(
		"Assemble Popper Op",
		"Food Prep Table 1",
		"5",
		"""- Top dough bite with fruit""",
	),
	(
		"Assemble Combination Product",
		"Food Prep Table 1",
		"5",
		"""- Tower: package one pie and one pocket, and one popper
    - Pocketful of Bay: package one pocket with two poppers""",
	),
]


attributes = {
	"Ambrosia Pie": {
		"Fruits": ["Hairless Rambutan", "Cloudberry", "Tayberry"],
		"Price": 11.00,
		"Color": ["Blue", "Red"],
		"Brand": "Chelsea Fruit Co",
	},
	"Double Plum Pie": {
		"Fruits": ["Cocoplum", "Damson Plum"],
		"Price": 10.50,
		"Color": ["Purple"],
		"Brand": "Chelsea Fruit Co",
	},
	"Gooseberry Pie": {
		"Fruits": "Gooseberry",
		"Price": 12.00,
		"Color": ["Yellow"],
		"Brand": "Chelsea Fruit Co",
	},
	"Kaduka Key Lime Pie": {
		"Fruits": ["Kaduka Lime", "Limequat"],
		"Price": 11.50,
		"Color": ["Green", "Yellow"],
		"Brand": "Chelsea Fruit Co",
	},
	"Tayberry": {
		"Color": ["Red"],
	},
	"Limequat": {
		"Color": ["Yellow", "Green"],
	},
	"Kaduka Lime": {
		"Color": ["Green"],
	},
	"Hairless Rambutan": {
		"Color": ["Red"],
	},
	"Gooseberry": {
		"Color": ["Yellow"],
	},
	"Damson Plum": {
		"Color": ["Purple"],
	},
	"Cocoplum": {
		"Color": ["Purple", "Black"],
	},
	"Bayberry": {
		"Color": ["Red", "Green", "Blue"],
	},
	"Sugar": {
		"Color": ["White"],
	},
	"Salt": {
		"Color": ["White"],
	},
	"Flour": {
		"Color": ["White"],
	},
	"Cornstarch": {
		"Color": ["White"],
	},
	"Butter": {
		"Color": ["Yellow"],
	},
	"Cloudberry": {
		"Color": ["Yellow", "Red"],
	},
}
<<<<<<< HEAD
=======

<<<<<<< HEAD
items_stockentry = {
	"Butter": {"qty": 46, "warehouse": "Refrigerator - APC"},
	"Cornstarch": {"qty": 2, "warehouse": "Storeroom - APC"},
	"Flour": {"qty": 68, "warehouse": "Storeroom - APC"},
	"Kaduka Lime": {"qty": 20, "warehouse": "Refrigerator - APC"},
	"Limequat": {"qty": 10, "warehouse": "Refrigerator - APC"},
	"Parchment Paper": {"qty": 80, "warehouse": "Storeroom - APC"},
	"Pie Tin": {"qty": 80, "warehouse": "Storeroom - APC"},
	"Pie Box": {"qty": 80, "warehouse": "Storeroom - APC"},
	"Salt": {"qty": 1, "warehouse": "Storeroom - APC"},
	"Sugar": {"qty": 8, "warehouse": "Storeroom - APC"},
	"Water": {"qty": 20, "warehouse": "Kitchen - APC"},
	"Cocoplum": {"qty": 45, "warehouse": "Refrigerator - APC"},
	"Damson Plum": {"qty": 45, "warehouse": "Refrigerator - APC"},
	"Cloudberry": {"qty": 45, "warehouse": "Refrigerator - APC"},
	"Hairless Rambutan": {"qty": 30, "warehouse": "Storeroom - APC"},
	"Tayberry": {"qty": 15, "warehouse": "Refrigerator - APC"},
	"Gooseberry": {"qty": 30, "warehouse": "Refrigerator - APC"},
}
>>>>>>> 8d8df6d (warehouse)
=======
items_stockentry = [
	{"item_code": "Butter", "qty": 44, "warehouse": "Refrigerator - APC"},
	{"item_code": "Bayberry", "qty": 82, "warehouse": "Refrigerator - APC"},
	{"item_code": "Cornstarch", "qty": 2, "warehouse": "Storeroom - APC"},
	{"item_code": "Flour", "qty": 71, "warehouse": "Storeroom - APC"},
	{"item_code": "Parchment Paper", "qty": 60, "warehouse": "Storeroom - APC"},
	{"item_code": "Pie Tin", "qty": 60, "warehouse": "Storeroom - APC"},
	{"item_code": "Pie Box", "qty": 70, "warehouse": "Storeroom - APC"},
	{"item_code": "Sugar", "qty": 8, "warehouse": "Storeroom - APC"},
	{"item_code": "Salt", "qty": 1, "warehouse": "Storeroom - APC"},
	{"item_code": "Water", "qty": 15, "warehouse": "Kitchen - APC"},
	{"item_code": "Gooseberry", "qty": 30, "warehouse": "Refrigerator - APC"},
	{"item_code": "Cocoplum", "qty": 45, "warehouse": "Refrigerator - APC"},
	{"item_code": "Damson Plum", "qty": 45, "warehouse": "Refrigerator - APC"},
	{"item_code": "Bilberry", "qty": 53, "warehouse": "Refrigerator - APC"},
	{"item_code": "Kepel", "qty": 37, "warehouse": "Refrigerator - APC"},
	{"item_code": "Lime", "qty": 74, "warehouse": "Refrigerator - APC"},
	{"item_code": "Boquila", "qty": 74, "warehouse": "Refrigerator - APC"},
	{"item_code": "Bael", "qty": 83, "warehouse": "Refrigerator - APC"},
	{"item_code": "Highbush Cranberry", "qty": 17, "warehouse": "Refrigerator - APC"},
	{"item_code": "Sambucus", "qty": 85, "warehouse": "Refrigerator - APC"},
	{"item_code": "Redcurrant", "qty": 78, "warehouse": "Refrigerator - APC"},
	{"item_code": "Gac", "qty": 73, "warehouse": "Refrigerator - APC"},
	{"item_code": "European Blueberry", "qty": 1, "warehouse": "Refrigerator - APC"},
	{"item_code": "Giant Granadilla", "qty": 51, "warehouse": "Refrigerator - APC"},
	{"item_code": "Bearberry", "qty": 45, "warehouse": "Refrigerator - APC"},
	{"item_code": "Seedless Watermelon", "qty": 77, "warehouse": "Refrigerator - APC"},
	{"item_code": "Mini Watermelon", "qty": 4, "warehouse": "Refrigerator - APC"},
	{"item_code": "Kandis", "qty": 62, "warehouse": "Refrigerator - APC"},
	{"item_code": "Berberis Vulgaris", "qty": 65, "warehouse": "Refrigerator - APC"},
	{"item_code": "Blue Tongue", "qty": 32, "warehouse": "Refrigerator - APC"},
	{"item_code": "Kahikatea", "qty": 34, "warehouse": "Refrigerator - APC"},
	{"item_code": "Kabosu", "qty": 92, "warehouse": "Refrigerator - APC"},
	{"item_code": "Kaffir Lime", "qty": 95, "warehouse": "Refrigerator - APC"},
	{"item_code": "Black Apple", "qty": 72, "warehouse": "Refrigerator - APC"},
	{"item_code": "Black Cherry", "qty": 39, "warehouse": "Refrigerator - APC"},
	{"item_code": "Lychee", "qty": 26, "warehouse": "Refrigerator - APC"},
	{"item_code": "Jostaberry", "qty": 34, "warehouse": "Refrigerator - APC"},
	{"item_code": "Camu Camu", "qty": 54, "warehouse": "Refrigerator - APC"},
	{"item_code": "Batuan", "qty": 3, "warehouse": "Refrigerator - APC"},
	{"item_code": "Calamondin", "qty": 50, "warehouse": "Refrigerator - APC"},
	{"item_code": "Citron", "qty": 12, "warehouse": "Refrigerator - APC"},
	{"item_code": "Coco Plum", "qty": 65, "warehouse": "Refrigerator - APC"},
	{"item_code": "Horned Melon", "qty": 54, "warehouse": "Refrigerator - APC"},
	{"item_code": "Fragaria", "qty": 5, "warehouse": "Refrigerator - APC"},
	{"item_code": "Boysenberry", "qty": 94, "warehouse": "Refrigerator - APC"},
	{"item_code": "Chokeberry", "qty": 94, "warehouse": "Refrigerator - APC"},
	{"item_code": "Raisin", "qty": 57, "warehouse": "Refrigerator - APC"},
	{"item_code": "Lawton Blackberry", "qty": 17, "warehouse": "Refrigerator - APC"},
	{"item_code": "Cranberry", "qty": 47, "warehouse": "Refrigerator - APC"},
	{"item_code": "Bilimbi", "qty": 23, "warehouse": "Refrigerator - APC"},
	{"item_code": "Barbados Cherry", "qty": 79, "warehouse": "Refrigerator - APC"},
	{"item_code": "Photinia", "qty": 85, "warehouse": "Refrigerator - APC"},
	{"item_code": "Doubah", "qty": 14, "warehouse": "Refrigerator - APC"},
	{"item_code": "Coffee", "qty": 66, "warehouse": "Refrigerator - APC"},
	{"item_code": "Youngberry", "qty": 75, "warehouse": "Refrigerator - APC"},
	{"item_code": "Bacuri", "qty": 51, "warehouse": "Refrigerator - APC"},
	{"item_code": "Louvi", "qty": 38, "warehouse": "Refrigerator - APC"},
	{"item_code": "Jaltomata Procumbens", "qty": 64, "warehouse": "Refrigerator - APC"},
	{"item_code": "Empetrum", "qty": 98, "warehouse": "Refrigerator - APC"},
	{"item_code": "European Raspberry", "qty": 38, "warehouse": "Refrigerator - APC"},
	{"item_code": "Black Raspberry", "qty": 50, "warehouse": "Refrigerator - APC"},
	{"item_code": "Cryptocarya Alba", "qty": 98, "warehouse": "Refrigerator - APC"},
	{"item_code": "Canary Melon", "qty": 82, "warehouse": "Refrigerator - APC"},
	{"item_code": "Biriba", "qty": 30, "warehouse": "Refrigerator - APC"},
	{"item_code": "Cocky Apple", "qty": 79, "warehouse": "Refrigerator - APC"},
	{"item_code": "Edible Honeysuckle", "qty": 91, "warehouse": "Refrigerator - APC"},
	{"item_code": "Whinberry", "qty": 51, "warehouse": "Refrigerator - APC"},
	{"item_code": "Desert Lime", "qty": 63, "warehouse": "Refrigerator - APC"},
	{"item_code": "Myrciaria Floribunda", "qty": 98, "warehouse": "Refrigerator - APC"},
	{"item_code": "Physalis", "qty": 52, "warehouse": "Refrigerator - APC"},
	{"item_code": "Bitter Melon", "qty": 38, "warehouse": "Refrigerator - APC"},
	{"item_code": "Dabai", "qty": 97, "warehouse": "Refrigerator - APC"},
	{"item_code": "Beach Plum", "qty": 88, "warehouse": "Refrigerator - APC"},
	{"item_code": "Melon Pear", "qty": 79, "warehouse": "Refrigerator - APC"},
	{"item_code": "Blood Orange", "qty": 30, "warehouse": "Refrigerator - APC"},
	{"item_code": "Banana", "qty": 51, "warehouse": "Refrigerator - APC"},
	{"item_code": "Loquat", "qty": 81, "warehouse": "Refrigerator - APC"},
	{"item_code": "Eugenia Uniflora", "qty": 5, "warehouse": "Refrigerator - APC"},
	{"item_code": "Kakadu Lime", "qty": 29, "warehouse": "Refrigerator - APC"},
	{"item_code": "Karonda", "qty": 4, "warehouse": "Refrigerator - APC"},
	{"item_code": "Hippophae", "qty": 10, "warehouse": "Refrigerator - APC"},
	{"item_code": "Guava", "qty": 56, "warehouse": "Refrigerator - APC"},
	{"item_code": "Candlenut", "qty": 17, "warehouse": "Refrigerator - APC"},
	{"item_code": "Tomatillo", "qty": 74, "warehouse": "Refrigerator - APC"},
	{"item_code": "Olallieberry", "qty": 17, "warehouse": "Refrigerator - APC"},
	{"item_code": "Date", "qty": 84, "warehouse": "Refrigerator - APC"},
	{"item_code": "Midyim", "qty": 88, "warehouse": "Refrigerator - APC"},
	{"item_code": "Cowberry", "qty": 69, "warehouse": "Refrigerator - APC"},
	{"item_code": "Kapok", "qty": 34, "warehouse": "Refrigerator - APC"},
	{"item_code": "Durian", "qty": 6, "warehouse": "Refrigerator - APC"},
	{"item_code": "Desert Banana", "qty": 53, "warehouse": "Refrigerator - APC"},
	{"item_code": "Coconut", "qty": 66, "warehouse": "Refrigerator - APC"},
	{"item_code": "Triphasia Brassii", "qty": 77, "warehouse": "Refrigerator - APC"},
	{"item_code": "Kiwifruit", "qty": 43, "warehouse": "Refrigerator - APC"},
	{"item_code": "Hackberry", "qty": 75, "warehouse": "Refrigerator - APC"},
	{"item_code": "Genip", "qty": 23, "warehouse": "Refrigerator - APC"},
	{"item_code": "Goji", "qty": 55, "warehouse": "Refrigerator - APC"},
	{"item_code": "Clementine", "qty": 80, "warehouse": "Refrigerator - APC"},
	{"item_code": "Huckleberry", "qty": 95, "warehouse": "Refrigerator - APC"},
	{"item_code": "Sultana", "qty": 75, "warehouse": "Refrigerator - APC"},
	{"item_code": "Bacupari", "qty": 16, "warehouse": "Refrigerator - APC"},
	{"item_code": "White Currant", "qty": 8, "warehouse": "Refrigerator - APC"},
	{"item_code": "Raspberry", "qty": 4, "warehouse": "Refrigerator - APC"},
]
<<<<<<< HEAD
>>>>>>> d1de7e2 (split by time for LIFO/FIFO)
=======

item_dimensions = [
	{
		"name": "Bilberry",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bilberry",
		"uom": "Box",
	},
	{
		"name": "Kepel",
		"item_length": 14.2,
		"item_height": 5.1,
		"item_width": 9.5,
		"item_weight": 7.2,
		"dimension_type": "Exterior",
		"case_height": 5.1,
		"case_width": 9.5,
		"case_length": 14.2,
		"case_weight": 7.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kepel",
		"uom": "Box",
	},
	{
		"name": "Lime",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 10.0,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 10.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Lime",
		"uom": "Box",
	},
	{
		"name": "Boquila",
		"item_length": 11.8,
		"item_height": 4.0,
		"item_width": 7.9,
		"item_weight": 4.8,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 7.9,
		"case_length": 11.8,
		"case_weight": 4.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Boquila",
		"uom": "Box",
	},
	{
		"name": "Bael",
		"item_length": 18.2,
		"item_height": 8.3,
		"item_width": 12.5,
		"item_weight": 15.5,
		"dimension_type": "Exterior",
		"case_height": 8.3,
		"case_width": 12.5,
		"case_length": 18.2,
		"case_weight": 15.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bael",
		"uom": "Box",
	},
	{
		"name": "Highbush Cranberry",
		"item_length": 13.1,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.2,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.1,
		"case_weight": 6.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Highbush Cranberry",
		"uom": "Box",
	},
	{
		"name": "Sambucus",
		"item_length": 12.8,
		"item_height": 4.3,
		"item_width": 8.5,
		"item_weight": 5.8,
		"dimension_type": "Exterior",
		"case_height": 4.3,
		"case_width": 8.5,
		"case_length": 12.8,
		"case_weight": 5.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Sambucus",
		"uom": "Box",
	},
	{
		"name": "Redcurrant",
		"item_length": 11.5,
		"item_height": 3.9,
		"item_width": 7.7,
		"item_weight": 4.5,
		"dimension_type": "Exterior",
		"case_height": 3.9,
		"case_width": 7.7,
		"case_length": 11.5,
		"case_weight": 4.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Redcurrant",
		"uom": "Box",
	},
	{
		"name": "Gac",
		"item_length": 16.5,
		"item_height": 7.2,
		"item_width": 11.2,
		"item_weight": 12.8,
		"dimension_type": "Exterior",
		"case_height": 7.2,
		"case_width": 11.2,
		"case_length": 16.5,
		"case_weight": 12.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Gac",
		"uom": "Box",
	},
	{
		"name": "European Blueberry",
		"item_length": 12.2,
		"item_height": 4.1,
		"item_width": 8.1,
		"item_weight": 5.2,
		"dimension_type": "Exterior",
		"case_height": 4.1,
		"case_width": 8.1,
		"case_length": 12.2,
		"case_weight": 5.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "European Blueberry",
		"uom": "Box",
	},
	{
		"name": "Giant Granadilla",
		"item_length": 20.5,
		"item_height": 9.5,
		"item_width": 14.2,
		"item_weight": 18.5,
		"dimension_type": "Exterior",
		"case_height": 9.5,
		"case_width": 14.2,
		"case_length": 20.5,
		"case_weight": 18.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Giant Granadilla",
		"uom": "Box",
	},
	{
		"name": "Bearberry",
		"item_length": 11.2,
		"item_height": 3.8,
		"item_width": 7.5,
		"item_weight": 4.2,
		"dimension_type": "Exterior",
		"case_height": 3.8,
		"case_width": 7.5,
		"case_length": 11.2,
		"case_weight": 4.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bearberry",
		"uom": "Box",
	},
	{
		"name": "Seedless Watermelon",
		"item_length": 24.0,
		"item_height": 12.0,
		"item_width": 16.0,
		"item_weight": 25.0,
		"dimension_type": "Exterior",
		"case_height": 12.0,
		"case_width": 16.0,
		"case_length": 24.0,
		"case_weight": 25.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Seedless Watermelon",
		"uom": "Box",
	},
	{
		"name": "Mini Watermelon",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.5,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Mini Watermelon",
		"uom": "Box",
	},
	{
		"name": "Kandis",
		"item_length": 13.5,
		"item_height": 4.6,
		"item_width": 9.0,
		"item_weight": 6.8,
		"dimension_type": "Exterior",
		"case_height": 4.6,
		"case_width": 9.0,
		"case_length": 13.5,
		"case_weight": 6.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kandis",
		"uom": "Box",
	},
	{
		"name": "Berberis Vulgaris",
		"item_length": 12.0,
		"item_height": 4.0,
		"item_width": 8.0,
		"item_weight": 5.0,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 8.0,
		"case_length": 12.0,
		"case_weight": 5.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Berberis Vulgaris",
		"uom": "Box",
	},
	{
		"name": "Blue Tongue",
		"item_length": 14.5,
		"item_height": 5.2,
		"item_width": 9.7,
		"item_weight": 7.5,
		"dimension_type": "Exterior",
		"case_height": 5.2,
		"case_width": 9.7,
		"case_length": 14.5,
		"case_weight": 7.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Blue Tongue",
		"uom": "Box",
	},
	{
		"name": "Kahikatea",
		"item_length": 15.5,
		"item_height": 6.5,
		"item_width": 10.5,
		"item_weight": 9.2,
		"dimension_type": "Exterior",
		"case_height": 6.5,
		"case_width": 10.5,
		"case_length": 15.5,
		"case_weight": 9.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kahikatea",
		"uom": "Box",
	},
	{
		"name": "Kabosu",
		"item_length": 15.2,
		"item_height": 6.2,
		"item_width": 10.2,
		"item_weight": 8.8,
		"dimension_type": "Exterior",
		"case_height": 6.2,
		"case_width": 10.2,
		"case_length": 15.2,
		"case_weight": 8.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kabosu",
		"uom": "Box",
	},
	{
		"name": "Kaffir Lime",
		"item_length": 13.8,
		"item_height": 4.8,
		"item_width": 9.2,
		"item_weight": 7.0,
		"dimension_type": "Exterior",
		"case_height": 4.8,
		"case_width": 9.2,
		"case_length": 13.8,
		"case_weight": 7.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kaffir Lime",
		"uom": "Box",
	},
	{
		"name": "Black Apple",
		"item_length": 15.8,
		"item_height": 6.8,
		"item_width": 10.7,
		"item_weight": 9.5,
		"dimension_type": "Exterior",
		"case_height": 6.8,
		"case_width": 10.7,
		"case_length": 15.8,
		"case_weight": 9.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Black Apple",
		"uom": "Box",
	},
	{
		"name": "Black Cherry",
		"item_length": 13.2,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.5,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.2,
		"case_weight": 6.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Black Cherry",
		"uom": "Box",
	},
	{
		"name": "Lychee",
		"item_length": 14.8,
		"item_height": 5.5,
		"item_width": 9.9,
		"item_weight": 8.0,
		"dimension_type": "Exterior",
		"case_height": 5.5,
		"case_width": 9.9,
		"case_length": 14.8,
		"case_weight": 8.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Lychee",
		"uom": "Box",
	},
	{
		"name": "Jostaberry",
		"item_length": 12.8,
		"item_height": 4.3,
		"item_width": 8.5,
		"item_weight": 5.8,
		"dimension_type": "Exterior",
		"case_height": 4.3,
		"case_width": 8.5,
		"case_length": 12.8,
		"case_weight": 5.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Jostaberry",
		"uom": "Box",
	},
	{
		"name": "Camu Camu",
		"item_length": 13.1,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.2,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.1,
		"case_weight": 6.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Camu Camu",
		"uom": "Box",
	},
	{
		"name": "Batuan",
		"item_length": 14.6,
		"item_height": 5.4,
		"item_width": 9.8,
		"item_weight": 7.8,
		"dimension_type": "Exterior",
		"case_height": 5.4,
		"case_width": 9.8,
		"case_length": 14.6,
		"case_weight": 7.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Batuan",
		"uom": "Box",
	},
	{
		"name": "Calamondin",
		"item_length": 14.2,
		"item_height": 5.1,
		"item_width": 9.5,
		"item_weight": 7.2,
		"dimension_type": "Exterior",
		"case_height": 5.1,
		"case_width": 9.5,
		"case_length": 14.2,
		"case_weight": 7.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Calamondin",
		"uom": "Box",
	},
	{
		"name": "Citron",
		"item_length": 16.2,
		"item_height": 7.0,
		"item_width": 11.0,
		"item_weight": 12.5,
		"dimension_type": "Exterior",
		"case_height": 7.0,
		"case_width": 11.0,
		"case_length": 16.2,
		"case_weight": 12.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Citron",
		"uom": "Box",
	},
	{
		"name": "Coco Plum",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 9.8,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 9.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Coco Plum",
		"uom": "Box",
	},
	{
		"name": "Horned Melon",
		"item_length": 16.5,
		"item_height": 7.2,
		"item_width": 11.2,
		"item_weight": 11.2,
		"dimension_type": "Exterior",
		"case_height": 7.2,
		"case_width": 11.2,
		"case_length": 16.5,
		"case_weight": 11.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Horned Melon",
		"uom": "Box",
	},
	{
		"name": "Fragaria",
		"item_length": 11.8,
		"item_height": 4.0,
		"item_width": 7.9,
		"item_weight": 4.8,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 7.9,
		"case_length": 11.8,
		"case_weight": 4.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Fragaria",
		"uom": "Box",
	},
	{
		"name": "Boysenberry",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Boysenberry",
		"uom": "Box",
	},
	{
		"name": "Chokeberry",
		"item_length": 12.2,
		"item_height": 4.1,
		"item_width": 8.1,
		"item_weight": 5.2,
		"dimension_type": "Exterior",
		"case_height": 4.1,
		"case_width": 8.1,
		"case_length": 12.2,
		"case_weight": 5.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Chokeberry",
		"uom": "Box",
	},
	{
		"name": "Raisin",
		"item_length": 13.0,
		"item_height": 4.4,
		"item_width": 8.7,
		"item_weight": 6.0,
		"dimension_type": "Exterior",
		"case_height": 4.4,
		"case_width": 8.7,
		"case_length": 13.0,
		"case_weight": 6.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Raisin",
		"uom": "Box",
	},
	{
		"name": "Lawton Blackberry",
		"item_length": 12.8,
		"item_height": 4.3,
		"item_width": 8.5,
		"item_weight": 5.8,
		"dimension_type": "Exterior",
		"case_height": 4.3,
		"case_width": 8.5,
		"case_length": 12.8,
		"case_weight": 5.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Lawton Blackberry",
		"uom": "Box",
	},
	{
		"name": "Cranberry",
		"item_length": 13.2,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.5,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.2,
		"case_weight": 6.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cranberry",
		"uom": "Box",
	},
	{
		"name": "Bilimbi",
		"item_length": 13.8,
		"item_height": 4.8,
		"item_width": 9.2,
		"item_weight": 7.0,
		"dimension_type": "Exterior",
		"case_height": 4.8,
		"case_width": 9.2,
		"case_length": 13.8,
		"case_weight": 7.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bilimbi",
		"uom": "Box",
	},
	{
		"name": "Barbados Cherry",
		"item_length": 13.5,
		"item_height": 4.6,
		"item_width": 9.0,
		"item_weight": 6.8,
		"dimension_type": "Exterior",
		"case_height": 4.6,
		"case_width": 9.0,
		"case_length": 13.5,
		"case_weight": 6.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Barbados Cherry",
		"uom": "Box",
	},
	{
		"name": "Photinia",
		"item_length": 14.5,
		"item_height": 5.2,
		"item_width": 9.7,
		"item_weight": 7.5,
		"dimension_type": "Exterior",
		"case_height": 5.2,
		"case_width": 9.7,
		"case_length": 14.5,
		"case_weight": 7.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Photinia",
		"uom": "Box",
	},
	{
		"name": "Doubah",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.2,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Doubah",
		"uom": "Box",
	},
	{
		"name": "Coffee",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 10.5,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 10.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Coffee",
		"uom": "Box",
	},
	{
		"name": "Youngberry",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Youngberry",
		"uom": "Box",
	},
	{
		"name": "Bacuri",
		"item_length": 17.5,
		"item_height": 8.0,
		"item_width": 12.0,
		"item_weight": 14.2,
		"dimension_type": "Exterior",
		"case_height": 8.0,
		"case_width": 12.0,
		"case_length": 17.5,
		"case_weight": 14.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bacuri",
		"uom": "Box",
	},
	{
		"name": "Louvi",
		"item_length": 15.2,
		"item_height": 6.2,
		"item_width": 10.2,
		"item_weight": 8.8,
		"dimension_type": "Exterior",
		"case_height": 6.2,
		"case_width": 10.2,
		"case_length": 15.2,
		"case_weight": 8.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Louvi",
		"uom": "Box",
	},
	{
		"name": "Jaltomata Procumbens",
		"item_length": 13.1,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.2,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.1,
		"case_weight": 6.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Jaltomata Procumbens",
		"uom": "Box",
	},
	{
		"name": "Empetrum",
		"item_length": 11.5,
		"item_height": 3.9,
		"item_width": 7.7,
		"item_weight": 4.5,
		"dimension_type": "Exterior",
		"case_height": 3.9,
		"case_width": 7.7,
		"case_length": 11.5,
		"case_weight": 4.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Empetrum",
		"uom": "Box",
	},
	{
		"name": "European Raspberry",
		"item_length": 12.2,
		"item_height": 4.1,
		"item_width": 8.1,
		"item_weight": 5.2,
		"dimension_type": "Exterior",
		"case_height": 4.1,
		"case_width": 8.1,
		"case_length": 12.2,
		"case_weight": 5.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "European Raspberry",
		"uom": "Box",
	},
	{
		"name": "Black Raspberry",
		"item_length": 12.0,
		"item_height": 4.0,
		"item_width": 8.0,
		"item_weight": 5.0,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 8.0,
		"case_length": 12.0,
		"case_weight": 5.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Black Raspberry",
		"uom": "Box",
	},
	{
		"name": "Cryptocarya Alba",
		"item_length": 15.5,
		"item_height": 6.5,
		"item_width": 10.5,
		"item_weight": 9.0,
		"dimension_type": "Exterior",
		"case_height": 6.5,
		"case_width": 10.5,
		"case_length": 15.5,
		"case_weight": 9.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cryptocarya Alba",
		"uom": "Box",
	},
	{
		"name": "Canary Melon",
		"item_length": 18.2,
		"item_height": 8.3,
		"item_width": 12.5,
		"item_weight": 15.5,
		"dimension_type": "Exterior",
		"case_height": 8.3,
		"case_width": 12.5,
		"case_length": 18.2,
		"case_weight": 15.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Canary Melon",
		"uom": "Box",
	},
	{
		"name": "Biriba",
		"item_length": 16.8,
		"item_height": 7.4,
		"item_width": 11.4,
		"item_weight": 11.8,
		"dimension_type": "Exterior",
		"case_height": 7.4,
		"case_width": 11.4,
		"case_length": 16.8,
		"case_weight": 11.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Biriba",
		"uom": "Box",
	},
	{
		"name": "Cocky Apple",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 10.2,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 10.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cocky Apple",
		"uom": "Box",
	},
	{
		"name": "Edible Honeysuckle",
		"item_length": 12.8,
		"item_height": 4.3,
		"item_width": 8.5,
		"item_weight": 5.8,
		"dimension_type": "Exterior",
		"case_height": 4.3,
		"case_width": 8.5,
		"case_length": 12.8,
		"case_weight": 5.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Edible Honeysuckle",
		"uom": "Box",
	},
	{
		"name": "Whinberry",
		"item_length": 11.8,
		"item_height": 4.0,
		"item_width": 7.9,
		"item_weight": 4.8,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 7.9,
		"case_length": 11.8,
		"case_weight": 4.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Whinberry",
		"uom": "Box",
	},
	{
		"name": "Desert Lime",
		"item_length": 14.2,
		"item_height": 5.1,
		"item_width": 9.5,
		"item_weight": 7.2,
		"dimension_type": "Exterior",
		"case_height": 5.1,
		"case_width": 9.5,
		"case_length": 14.2,
		"case_weight": 7.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Desert Lime",
		"uom": "Box",
	},
	{
		"name": "Myrciaria Floribunda",
		"item_length": 13.2,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.5,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.2,
		"case_weight": 6.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Myrciaria Floribunda",
		"uom": "Box",
	},
	{
		"name": "Physalis",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Physalis",
		"uom": "Box",
	},
	{
		"name": "Bitter Melon",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 12.0,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 12.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bitter Melon",
		"uom": "Box",
	},
	{
		"name": "Dabai",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.5,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Dabai",
		"uom": "Box",
	},
	{
		"name": "Beach Plum",
		"item_length": 14.6,
		"item_height": 5.4,
		"item_width": 9.8,
		"item_weight": 7.8,
		"dimension_type": "Exterior",
		"case_height": 5.4,
		"case_width": 9.8,
		"case_length": 14.6,
		"case_weight": 7.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Beach Plum",
		"uom": "Box",
	},
	{
		"name": "Melon Pear",
		"item_length": 17.0,
		"item_height": 7.5,
		"item_width": 11.5,
		"item_weight": 13.5,
		"dimension_type": "Exterior",
		"case_height": 7.5,
		"case_width": 11.5,
		"case_length": 17.0,
		"case_weight": 13.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Melon Pear",
		"uom": "Box",
	},
	{
		"name": "Blood Orange",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 12.0,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 12.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Blood Orange",
		"uom": "Box",
	},
	{
		"name": "Banana",
		"item_length": 22.0,
		"item_height": 10.0,
		"item_width": 15.0,
		"item_weight": 20.0,
		"dimension_type": "Exterior",
		"case_height": 10.0,
		"case_width": 15.0,
		"case_length": 22.0,
		"case_weight": 20.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Banana",
		"uom": "Box",
	},
	{
		"name": "Loquat",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.2,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Loquat",
		"uom": "Box",
	},
	{
		"name": "Eugenia Uniflora",
		"item_length": 13.5,
		"item_height": 4.6,
		"item_width": 9.0,
		"item_weight": 6.8,
		"dimension_type": "Exterior",
		"case_height": 4.6,
		"case_width": 9.0,
		"case_length": 13.5,
		"case_weight": 6.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Eugenia Uniflora",
		"uom": "Box",
	},
	{
		"name": "Kakadu Lime",
		"item_length": 13.8,
		"item_height": 4.8,
		"item_width": 9.2,
		"item_weight": 7.0,
		"dimension_type": "Exterior",
		"case_height": 4.8,
		"case_width": 9.2,
		"case_length": 13.8,
		"case_weight": 7.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kakadu Lime",
		"uom": "Box",
	},
	{
		"name": "Karonda",
		"item_length": 14.5,
		"item_height": 5.2,
		"item_width": 9.7,
		"item_weight": 7.5,
		"dimension_type": "Exterior",
		"case_height": 5.2,
		"case_width": 9.7,
		"case_length": 14.5,
		"case_weight": 7.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Karonda",
		"uom": "Box",
	},
	{
		"name": "Hippophae",
		"item_length": 13.1,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.2,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.1,
		"case_weight": 6.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Hippophae",
		"uom": "Box",
	},
	{
		"name": "Guava",
		"item_length": 16.5,
		"item_height": 7.2,
		"item_width": 11.2,
		"item_weight": 11.5,
		"dimension_type": "Exterior",
		"case_height": 7.2,
		"case_width": 11.2,
		"case_length": 16.5,
		"case_weight": 11.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Guava",
		"uom": "Box",
	},
	{
		"name": "Candlenut",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 9.8,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 9.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Candlenut",
		"uom": "Box",
	},
	{
		"name": "Tomatillo",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.5,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Tomatillo",
		"uom": "Box",
	},
	{
		"name": "Olallieberry",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Olallieberry",
		"uom": "Box",
	},
	{
		"name": "Date",
		"item_length": 15.2,
		"item_height": 6.2,
		"item_width": 10.2,
		"item_weight": 8.8,
		"dimension_type": "Exterior",
		"case_height": 6.2,
		"case_width": 10.2,
		"case_length": 15.2,
		"case_weight": 8.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Date",
		"uom": "Box",
	},
	{
		"name": "Midyim",
		"item_length": 12.2,
		"item_height": 4.1,
		"item_width": 8.1,
		"item_weight": 5.2,
		"dimension_type": "Exterior",
		"case_height": 4.1,
		"case_width": 8.1,
		"case_length": 12.2,
		"case_weight": 5.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Midyim",
		"uom": "Box",
	},
	{
		"name": "Cowberry",
		"item_length": 11.8,
		"item_height": 4.0,
		"item_width": 7.9,
		"item_weight": 4.8,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 7.9,
		"case_length": 11.8,
		"case_weight": 4.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cowberry",
		"uom": "Box",
	},
	{
		"name": "Kapok",
		"item_length": 14.2,
		"item_height": 5.1,
		"item_width": 9.5,
		"item_weight": 7.2,
		"dimension_type": "Exterior",
		"case_height": 5.1,
		"case_width": 9.5,
		"case_length": 14.2,
		"case_weight": 7.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kapok",
		"uom": "Box",
	},
	{
		"name": "Durian",
		"item_length": 28.0,
		"item_height": 15.0,
		"item_width": 20.0,
		"item_weight": 35.0,
		"dimension_type": "Exterior",
		"case_height": 15.0,
		"case_width": 20.0,
		"case_length": 28.0,
		"case_weight": 35.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Durian",
		"uom": "Box",
	},
	{
		"name": "Desert Banana",
		"item_length": 20.5,
		"item_height": 9.5,
		"item_width": 14.2,
		"item_weight": 18.5,
		"dimension_type": "Exterior",
		"case_height": 9.5,
		"case_width": 14.2,
		"case_length": 20.5,
		"case_weight": 18.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Desert Banana",
		"uom": "Box",
	},
	{
		"name": "Coconut",
		"item_length": 26.0,
		"item_height": 13.0,
		"item_width": 18.0,
		"item_weight": 30.0,
		"dimension_type": "Exterior",
		"case_height": 13.0,
		"case_width": 18.0,
		"case_length": 26.0,
		"case_weight": 30.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Coconut",
		"uom": "Box",
	},
	{
		"name": "Triphasia Brassii",
		"item_length": 14.6,
		"item_height": 5.4,
		"item_width": 9.8,
		"item_weight": 7.8,
		"dimension_type": "Exterior",
		"case_height": 5.4,
		"case_width": 9.8,
		"case_length": 14.6,
		"case_weight": 7.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Triphasia Brassii",
		"uom": "Box",
	},
	{
		"name": "Kiwifruit",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 12.0,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 12.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Kiwifruit",
		"uom": "Box",
	},
	{
		"name": "Hackberry",
		"item_length": 13.2,
		"item_height": 4.5,
		"item_width": 8.8,
		"item_weight": 6.5,
		"dimension_type": "Exterior",
		"case_height": 4.5,
		"case_width": 8.8,
		"case_length": 13.2,
		"case_weight": 6.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Hackberry",
		"uom": "Box",
	},
	{
		"name": "Genip",
		"item_length": 15.0,
		"item_height": 6.0,
		"item_width": 10.0,
		"item_weight": 8.2,
		"dimension_type": "Exterior",
		"case_height": 6.0,
		"case_width": 10.0,
		"case_length": 15.0,
		"case_weight": 8.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Genip",
		"uom": "Box",
	},
	{
		"name": "Goji",
		"item_length": 12.8,
		"item_height": 4.3,
		"item_width": 8.5,
		"item_weight": 5.8,
		"dimension_type": "Exterior",
		"case_height": 4.3,
		"case_width": 8.5,
		"case_length": 12.8,
		"case_weight": 5.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Goji",
		"uom": "Box",
	},
	{
		"name": "Clementine",
		"item_length": 16.0,
		"item_height": 6.9,
		"item_width": 10.8,
		"item_weight": 10.5,
		"dimension_type": "Exterior",
		"case_height": 6.9,
		"case_width": 10.8,
		"case_length": 16.0,
		"case_weight": 10.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Clementine",
		"uom": "Box",
	},
	{
		"name": "Huckleberry",
		"item_length": 11.5,
		"item_height": 3.9,
		"item_width": 7.7,
		"item_weight": 4.5,
		"dimension_type": "Exterior",
		"case_height": 3.9,
		"case_width": 7.7,
		"case_length": 11.5,
		"case_weight": 4.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Huckleberry",
		"uom": "Box",
	},
	{
		"name": "Sultana",
		"item_length": 13.0,
		"item_height": 4.4,
		"item_width": 8.7,
		"item_weight": 6.0,
		"dimension_type": "Exterior",
		"case_height": 4.4,
		"case_width": 8.7,
		"case_length": 13.0,
		"case_weight": 6.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Sultana",
		"uom": "Box",
	},
	{
		"name": "Hairless Rambutan",
		"item_length": 15.8,
		"item_height": 6.8,
		"item_width": 10.7,
		"item_weight": 9.5,
		"dimension_type": "Exterior",
		"case_height": 6.8,
		"case_width": 10.7,
		"case_length": 15.8,
		"case_weight": 9.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Hairless Rambutan",
		"uom": "Box",
	},
	{
		"name": "Tayberry",
		"item_length": 12.5,
		"item_height": 4.2,
		"item_width": 8.3,
		"item_weight": 5.5,
		"dimension_type": "Exterior",
		"case_height": 4.2,
		"case_width": 8.3,
		"case_length": 12.5,
		"case_weight": 5.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Tayberry",
		"uom": "Box",
	},
	{
		"name": "Gooseberry",
		"item_length": 12.2,
		"item_height": 4.1,
		"item_width": 8.1,
		"item_weight": 5.2,
		"dimension_type": "Exterior",
		"case_height": 4.1,
		"case_width": 8.1,
		"case_length": 12.2,
		"case_weight": 5.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Gooseberry",
		"uom": "Box",
	},
	{
		"name": "Cocoplum",
		"item_length": 15.2,
		"item_height": 6.2,
		"item_width": 10.2,
		"item_weight": 8.8,
		"dimension_type": "Exterior",
		"case_height": 6.2,
		"case_width": 10.2,
		"case_length": 15.2,
		"case_weight": 8.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cocoplum",
		"uom": "Box",
	},
	{
		"name": "Damson Plum",
		"item_length": 14.5,
		"item_height": 5.2,
		"item_width": 9.7,
		"item_weight": 7.5,
		"dimension_type": "Exterior",
		"case_height": 5.2,
		"case_width": 9.7,
		"case_length": 14.5,
		"case_weight": 7.5,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Damson Plum",
		"uom": "Box",
	},
	{
		"name": "Bacupari",
		"item_length": 15.5,
		"item_height": 6.5,
		"item_width": 10.5,
		"item_weight": 9.2,
		"dimension_type": "Exterior",
		"case_height": 6.5,
		"case_width": 10.5,
		"case_length": 15.5,
		"case_weight": 9.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Bacupari",
		"uom": "Box",
	},
	{
		"name": "White Currant",
		"item_length": 11.8,
		"item_height": 4.0,
		"item_width": 7.9,
		"item_weight": 4.8,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 7.9,
		"case_length": 11.8,
		"case_weight": 4.8,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "White Currant",
		"uom": "Box",
	},
	{
		"name": "Raspberry",
		"item_length": 12.0,
		"item_height": 4.0,
		"item_width": 8.0,
		"item_weight": 5.0,
		"dimension_type": "Exterior",
		"case_height": 4.0,
		"case_width": 8.0,
		"case_length": 12.0,
		"case_weight": 5.0,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Raspberry",
		"uom": "Box",
	},
	{
		"name": "Limequat",
		"item_length": 14.2,
		"item_height": 5.1,
		"item_width": 9.5,
		"item_weight": 7.2,
		"dimension_type": "Exterior",
		"case_height": 5.1,
		"case_width": 9.5,
		"case_length": 14.2,
		"case_weight": 7.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Limequat",
		"uom": "Box",
	},
	{
		"name": "Cloudberry",
		"item_length": 11.2,
		"item_height": 3.8,
		"item_width": 7.5,
		"item_weight": 4.2,
		"dimension_type": "Exterior",
		"case_height": 3.8,
		"case_width": 7.5,
		"case_length": 11.2,
		"case_weight": 4.2,
		"orientation": 1,
		"reference_doctype": "Item",
		"reference_docname": "Cloudberry",
		"uom": "Box",
	},
]
>>>>>>> d0203e6 (item dimension data and bugfix)
